//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Microsoft.Graphics.Canvas.Geometry;
using Microsoft.UI.Xaml.Controls;
using System;
using System.Numerics;
using Windows.UI;
using Windows.UI.Composition;

namespace AnimatedVisuals
{
    sealed class Gift_popup : IAnimatedVisualSource
    {
        public IAnimatedVisual TryCreateAnimatedVisual(Compositor compositor, out object diagnostics)
        {
            diagnostics = null;
            if (!IsRuntimeCompatible())
            {
                return null;
            }
            return new AnimatedVisual(compositor);
        }

        static bool IsRuntimeCompatible()
        {
            if (!Windows.Foundation.Metadata.ApiInformation.IsTypePresent("Windows.UI.Composition.CompositionGeometricClip"))
            {
                return false;
            }
            return true;
        }

        sealed class AnimatedVisual : IAnimatedVisual
        {
            const long c_durationTicks = 23330000;
            readonly Compositor _c;
            readonly ExpressionAnimation _reusableExpressionAnimation;
            CompositionColorBrush _colorBrush_AlmostDarkCyan_FF1F9B7C;
            CompositionColorBrush _colorBrush_AlmostDarkSlateGray_FF374346;
            CompositionColorBrush _colorBrush_AlmostDarkSlateGray_FF485A5E;
            CompositionColorBrush _colorBrush_AlmostLightSeaGreen_FF23BC9C;
            CompositionColorBrush _colorBrush_AlmostSlateGray_FF677C7E;
            CompositionColorBrush _colorBrush_AlmostSlateGray_FF6C8488;
            CubicBezierEasingFunction _cubicBezierEasingFunction_0;
            StepEasingFunction _holdThenStepEasingFunction;
            ContainerVisual _root;
            ScalarKeyFrameAnimation _scalarAnimation_0_to_1_0;
            ExpressionAnimation _scalarExpressionAnimation;
            StepEasingFunction _stepThenHoldEasingFunction;

            // Layer (Shape): gift Outlines
            //   Path 1
            CompositionColorBrush ColorBrush_AlmostDarkCyan_FF1E9579()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0x1E, 0x95, 0x79));
            }

            CompositionColorBrush ColorBrush_AlmostDarkCyan_FF1F9B7C()
            {
                return _colorBrush_AlmostDarkCyan_FF1F9B7C = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x1F, 0x9B, 0x7C));
            }

            // Layer (Shape): coin Outlines
            //   Path 1
            CompositionColorBrush ColorBrush_AlmostDarkKhaki_FFD2BE6A()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0xD2, 0xBE, 0x6A));
            }

            // Layer (Shape): gift Outlines
            //   Path 1
            CompositionColorBrush ColorBrush_AlmostDarkSlateGray_FF2B3D51()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0x2B, 0x3D, 0x51));
            }

            // Layer (Shape): gift Outlines
            //   Path 1
            CompositionColorBrush ColorBrush_AlmostDarkSlateGray_FF2C4653()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0x2C, 0x46, 0x53));
            }

            CompositionColorBrush ColorBrush_AlmostDarkSlateGray_FF374346()
            {
                return _colorBrush_AlmostDarkSlateGray_FF374346 = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x37, 0x43, 0x46));
            }

            // Layer (Shape): gift Outlines
            //   Path 1
            CompositionColorBrush ColorBrush_AlmostDarkSlateGray_FF3D5A71()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0x3D, 0x5A, 0x71));
            }

            // Layer (Shape): boxBack Outlines
            //   Path 1
            CompositionColorBrush ColorBrush_AlmostDarkSlateGray_FF404F51()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0x40, 0x4F, 0x51));
            }

            CompositionColorBrush ColorBrush_AlmostDarkSlateGray_FF485A5E()
            {
                return _colorBrush_AlmostDarkSlateGray_FF485A5E = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x48, 0x5A, 0x5E));
            }

            // Layer (Shape): coin Outlines
            //   Path 1
            CompositionColorBrush ColorBrush_AlmostKhaki_FFF4E879()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0xF4, 0xE8, 0x79));
            }

            CompositionColorBrush ColorBrush_AlmostLightSeaGreen_FF23BC9C()
            {
                return _colorBrush_AlmostLightSeaGreen_FF23BC9C = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x23, 0xBC, 0x9C));
            }

            // Layer (Shape): gift Outlines
            //   Path 1
            CompositionColorBrush ColorBrush_AlmostMediumSeaGreen_FF22A281()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0x22, 0xA2, 0x81));
            }

            CompositionColorBrush ColorBrush_AlmostSlateGray_FF677C7E()
            {
                return _colorBrush_AlmostSlateGray_FF677C7E = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x67, 0x7C, 0x7E));
            }

            CompositionColorBrush ColorBrush_AlmostSlateGray_FF6C8488()
            {
                return _colorBrush_AlmostSlateGray_FF6C8488 = _c.CreateColorBrush(Color.FromArgb(0xFF, 0x6C, 0x84, 0x88));
            }

            CompositionColorBrush ColorBrush_White()
            {
                return _c.CreateColorBrush(Color.FromArgb(0xFF, 0xFF, 0xFF, 0xFF));
            }

            // Layer (Shape): boxBack Outlines
            CompositionContainerShape ContainerShape_0()
            {
                var result = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Position", new Vector2(540.01001F, 895.005005F));
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_00());
                shapes.Add(SpriteShape_01());
                shapes.Add(SpriteShape_02());
                shapes.Add(SpriteShape_03());
                result.StartAnimation("Position", Vector2Animation_0());
                var controller = result.TryGetAnimationController("Position");
                controller.Pause();
                controller.StartAnimation("Progress", ScalarExpressionAnimation());
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "my.Position - Vector2(344.219,390.696)";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("Offset", _reusableExpressionAnimation);
                return result;
            }

            // Layer (Shape): coin Outlines
            CompositionContainerShape ContainerShape_1()
            {
                var result = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Position", new Vector2(538.924988F, 399.328003F));
                result.CenterPoint = new Vector2(86.4449997F, 115.357002F);
                result.Scale = new Vector2(0, 0);
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_04());
                shapes.Add(SpriteShape_05());
                shapes.Add(SpriteShape_06());
                result.StartAnimation("Position", Vector2Animation_1());
                var controller = result.TryGetAnimationController("Position");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "my.Position - Vector2(86.445,115.357)";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("Offset", _reusableExpressionAnimation);
                result.StartAnimation("Scale", Vector2Animation_2());
                controller = result.TryGetAnimationController("Scale");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            // Layer (Shape): gift Outlines
            CompositionContainerShape ContainerShape_2()
            {
                var result = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Position", new Vector2(539.692017F, 1032.44299F));
                result.CenterPoint = new Vector2(201.169998F, 232.363007F);
                result.Scale = new Vector2(0.620000005F, 0.620000005F);
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_07());
                shapes.Add(SpriteShape_08());
                shapes.Add(SpriteShape_09());
                shapes.Add(SpriteShape_10());
                shapes.Add(SpriteShape_11());
                shapes.Add(SpriteShape_12());
                shapes.Add(SpriteShape_13());
                shapes.Add(SpriteShape_14());
                shapes.Add(SpriteShape_15());
                shapes.Add(SpriteShape_16());
                shapes.Add(SpriteShape_17());
                shapes.Add(SpriteShape_18());
                result.StartAnimation("Position", Vector2Animation_3());
                var controller = result.TryGetAnimationController("Position");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "my.Position - Vector2(201.17,232.363)";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("Offset", _reusableExpressionAnimation);
                result.StartAnimation("Scale", Vector2Animation_4());
                controller = result.TryGetAnimationController("Scale");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            // Layer (Shape): boxFront Outlines
            CompositionContainerShape ContainerShape_3()
            {
                var result = _c.CreateContainerShape();
                var propertySet = result.Properties;
                propertySet.InsertVector2("Position", new Vector2(542.405029F, 882.914978F));
                var shapes = result.Shapes;
                shapes.Add(SpriteShape_19());
                shapes.Add(SpriteShape_20());
                shapes.Add(SpriteShape_21());
                shapes.Add(SpriteShape_22());
                result.StartAnimation("Position", Vector2Animation_5());
                var controller = result.TryGetAnimationController("Position");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                _reusableExpressionAnimation.ClearAllParameters();
                _reusableExpressionAnimation.Expression = "my.Position - Vector2(388.775,142.97)";
                _reusableExpressionAnimation.SetReferenceParameter("my", result);
                result.StartAnimation("Offset", _reusableExpressionAnimation);
                return result;
            }

            CubicBezierEasingFunction CubicBezierEasingFunction_0()
            {
                return _cubicBezierEasingFunction_0 = _c.CreateCubicBezierEasingFunction(new Vector2(0.166999996F, 0.166999996F), new Vector2(0.833000004F, 0.833000004F));
            }

            // Layer (Shape): coin Outlines
            //   Position
            CubicBezierEasingFunction CubicBezierEasingFunction_1()
            {
                return _c.CreateCubicBezierEasingFunction(new Vector2(0.333000004F, 0), new Vector2(0.833000004F, 0.833000004F));
            }

            CanvasGeometry Geometry_00()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(0.00200000009F, -149.149994F));
                    builder.AddLine(new Vector2(-257.618988F, 0));
                    builder.AddLine(new Vector2(0.00200000009F, 149.149994F));
                    builder.AddLine(new Vector2(257.618988F, 0));
                    builder.AddLine(new Vector2(0.00200000009F, -149.149994F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_01()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(128.811005F, -223.723007F));
                    builder.AddLine(new Vector2(-128.811005F, -74.5759964F));
                    builder.AddLine(new Vector2(-128.811005F, 223.723007F));
                    builder.AddLine(new Vector2(128.811005F, 74.5739975F));
                    builder.AddLine(new Vector2(128.811005F, -223.723007F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_02()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-171.746994F, 28.4500008F));
                    builder.AddLine(new Vector2(-85.8769989F, 118.139999F));
                    builder.AddLine(new Vector2(171.746994F, -31.0060005F));
                    builder.AddLine(new Vector2(85.8669968F, -118.139999F));
                    builder.AddLine(new Vector2(-171.746994F, 28.4500008F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_03()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(85.439003F, 77.1900024F));
                    builder.AddLine(new Vector2(172.179001F, 72.9629974F));
                    builder.AddLine(new Vector2(-87.1760025F, -77.1900024F));
                    builder.AddLine(new Vector2(-172.177994F, -71.9550018F));
                    builder.AddLine(new Vector2(85.439003F, 77.1900024F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_04()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(0.00100000005F, -90.3720016F));
                    builder.AddCubicBezier(new Vector2(-19.9570007F, -101.929001F), new Vector2(-38.1539993F, -103.764F), new Vector2(-51.9379997F, -97.4509964F));
                    builder.AddCubicBezier(new Vector2(-52.9410019F, -96.9919968F), new Vector2(-59.1189995F, -94.2649994F), new Vector2(-70.473999F, -89.2679977F));
                    builder.AddLine(new Vector2(-67.7490005F, -83.8919983F));
                    builder.AddCubicBezier(new Vector2(-74.1969986F, -74.4869995F), new Vector2(-77.8960037F, -61.4500008F), new Vector2(-77.8960037F, -45.2599983F));
                    builder.AddCubicBezier(new Vector2(-77.8960037F, 4.5710001F), new Vector2(-43.019001F, 65.163002F), new Vector2(0.00100000005F, 90.0790024F));
                    builder.AddCubicBezier(new Vector2(12.9060001F, 97.552002F), new Vector2(26.559F, 103.764F), new Vector2(37.2770004F, 103.536003F));
                    builder.AddLine(new Vector2(54.9080009F, 95.6460037F));
                    builder.AddCubicBezier(new Vector2(69.1050034F, 87.5220032F), new Vector2(77.8960037F, 69.9810028F), new Vector2(77.8960037F, 44.9669991F));
                    builder.AddCubicBezier(new Vector2(77.8960037F, -4.86399984F), new Vector2(43.0209999F, -65.4560013F), new Vector2(0.00100000005F, -90.3720016F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_05()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(77.8970032F, 45.112999F));
                    builder.AddCubicBezier(new Vector2(77.8970032F, 94.9440002F), new Vector2(43.019001F, 115.139999F), new Vector2(0, 90.2249985F));
                    builder.AddCubicBezier(new Vector2(-43.0200005F, 65.3089981F), new Vector2(-77.8970032F, 4.71700001F), new Vector2(-77.8970032F, -45.1139984F));
                    builder.AddCubicBezier(new Vector2(-77.8970032F, -94.9449997F), new Vector2(-43.0200005F, -115.140999F), new Vector2(0, -90.2259979F));
                    builder.AddCubicBezier(new Vector2(43.019001F, -65.3099976F), new Vector2(77.8970032F, -4.71799994F), new Vector2(77.8970032F, 45.112999F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_06()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(16.2970009F, 14.6429996F));
                    builder.AddLine(new Vector2(15.9680004F, 14.5970001F));
                    builder.AddLine(new Vector2(-8.20899963F, 0.593999982F));
                    builder.AddLine(new Vector2(23.9249992F, -18.8209991F));
                    builder.AddLine(new Vector2(16.2970009F, 14.6429996F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    builder.BeginFigure(new Vector2(-24.3460007F, 27.3360004F));
                    builder.AddLine(new Vector2(-24.3460007F, 10.3439999F));
                    builder.AddLine(new Vector2(-9.82999992F, 1.57599998F));
                    builder.AddLine(new Vector2(-9.82999992F, 55.0519981F));
                    builder.AddLine(new Vector2(-9.92500019F, 55.6430016F));
                    builder.AddLine(new Vector2(-24.3460007F, 27.3360004F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    builder.BeginFigure(new Vector2(-9.82999992F, -55.7939987F));
                    builder.AddLine(new Vector2(-9.82999992F, -0.944999993F));
                    builder.AddLine(new Vector2(-24.3460007F, -26.6280003F));
                    builder.AddLine(new Vector2(-24.3460007F, -57.1329994F));
                    builder.AddLine(new Vector2(-9.82999992F, -55.7939987F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    builder.BeginFigure(new Vector2(-8.8920002F, -55.2480011F));
                    builder.AddLine(new Vector2(23.7660007F, -20.2740002F));
                    builder.AddLine(new Vector2(-8.8920002F, -0.541000009F));
                    builder.AddLine(new Vector2(-8.8920002F, -55.2480011F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    builder.BeginFigure(new Vector2(-3.09899998F, 12.5240002F));
                    builder.AddLine(new Vector2(-8.8920002F, 49.1399994F));
                    builder.AddLine(new Vector2(-8.8920002F, 2.26799989F));
                    builder.AddLine(new Vector2(-3.09899998F, 12.5240002F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    builder.BeginFigure(new Vector2(-8.41499996F, 1.55999994F));
                    builder.AddLine(new Vector2(13.4770002F, 14.2399998F));
                    builder.AddLine(new Vector2(-2.55100012F, 11.9350004F));
                    builder.AddLine(new Vector2(-8.41499996F, 1.55999994F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    builder.BeginFigure(new Vector2(-24.3460007F, -7.66599989F));
                    builder.AddLine(new Vector2(-10.4350004F, 0.391000003F));
                    builder.AddLine(new Vector2(-24.3460007F, 8.79199982F));
                    builder.AddLine(new Vector2(-24.3460007F, -7.66599989F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    builder.BeginFigure(new Vector2(-24.3460007F, -25.073F));
                    builder.AddLine(new Vector2(-10.6350002F, -0.810000002F));
                    builder.AddLine(new Vector2(-24.3460007F, -8.74800014F));
                    builder.AddLine(new Vector2(-24.3460007F, -25.073F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    builder.BeginFigure(new Vector2(-9.17500019F, -56.9420013F));
                    builder.AddLine(new Vector2(-25.6590004F, -58.8979988F));
                    builder.AddLine(new Vector2(-25.6590004F, 27.2269993F));
                    builder.AddLine(new Vector2(-9.17500019F, 58.8979988F));
                    builder.AddLine(new Vector2(-1.87199998F, 13.6689997F));
                    builder.AddLine(new Vector2(17.4190006F, 16.3799992F));
                    builder.AddLine(new Vector2(25.6590004F, -19.8490009F));
                    builder.AddLine(new Vector2(-9.17500019F, -56.9420013F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_07()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-100.489998F, 58.1230011F));
                    builder.AddLine(new Vector2(100.489998F, 174.369995F));
                    builder.AddLine(new Vector2(100.489998F, -58.1199989F));
                    builder.AddLine(new Vector2(-100.489998F, -174.371002F));
                    builder.AddLine(new Vector2(-100.489998F, 58.1230011F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_08()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-100.489998F, -58.1199989F));
                    builder.AddLine(new Vector2(-100.489998F, 174.369995F));
                    builder.AddLine(new Vector2(100.489998F, 58.1230011F));
                    builder.AddLine(new Vector2(100.489998F, -174.369995F));
                    builder.AddLine(new Vector2(-100.489998F, -58.1199989F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_09()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-200.977997F, -0.00400000019F));
                    builder.AddLine(new Vector2(0.00100000005F, 116.246002F));
                    builder.AddLine(new Vector2(200.977997F, -0.00400000019F));
                    builder.AddLine(new Vector2(0.00100000005F, -116.246002F));
                    builder.AddLine(new Vector2(-200.977997F, -0.00400000019F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_10()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(17.1280003F, -106.338997F));
                    builder.AddLine(new Vector2(17.1280003F, 126.153999F));
                    builder.AddLine(new Vector2(-17.1280003F, 106.336998F));
                    builder.AddLine(new Vector2(-17.1280003F, -126.153F));
                    builder.AddLine(new Vector2(17.1280003F, -106.338997F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_11()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(83.3610001F, 68.0309982F));
                    builder.AddLine(new Vector2(-117.616997F, -48.2159996F));
                    builder.AddLine(new Vector2(-83.3639984F, -68.0309982F));
                    builder.AddLine(new Vector2(117.616997F, 48.2200012F));
                    builder.AddLine(new Vector2(83.3610001F, 68.0309982F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_12()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(17.1280003F, -126.153999F));
                    builder.AddLine(new Vector2(17.1280003F, 106.339996F));
                    builder.AddLine(new Vector2(-17.1280003F, 126.153999F));
                    builder.AddLine(new Vector2(-17.1280003F, -106.339996F));
                    builder.AddLine(new Vector2(17.1280003F, -126.153999F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_13()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(117.615997F, -48.2150002F));
                    builder.AddLine(new Vector2(-83.3600006F, 68.0289993F));
                    builder.AddLine(new Vector2(-117.615997F, 48.2159996F));
                    builder.AddLine(new Vector2(83.3600006F, -68.0289993F));
                    builder.AddLine(new Vector2(117.615997F, -48.2150002F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_14()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(1.26699996F, -0.897000015F));
                    builder.AddLine(new Vector2(-1.26699996F, 0.897000015F));
                    builder.AddCubicBezier(new Vector2(-0.546000004F, 0.282000005F), new Vector2(0.308999985F, -0.333999991F), new Vector2(1.26699996F, -0.897000015F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_15()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(57.3419991F, 46.1769981F));
                    builder.AddLine(new Vector2(57.2900009F, 46.1500015F));
                    builder.AddCubicBezier(new Vector2(54.2490005F, 44.7879982F), new Vector2(-57.3419991F, -5.31899977F), new Vector2(-23.2579994F, -25.6130009F));
                    builder.AddCubicBezier(new Vector2(11.2799997F, -46.1769981F), new Vector2(57.3419991F, 46.1769981F), new Vector2(57.3419991F, 46.1769981F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_16()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(40.3569984F, 29.559F));
                    builder.AddLine(new Vector2(39.6360016F, 30.0429993F));
                    builder.AddLine(new Vector2(39.3950005F, 30.2269993F));
                    builder.AddLine(new Vector2(39.368F, 30.2269993F));
                    builder.AddCubicBezier(new Vector2(25.6480007F, 37.2879982F), new Vector2(-41.1780014F, -10.2519999F), new Vector2(-43.1020012F, -11.6429996F));
                    builder.AddLine(new Vector2(-43.1570015F, -11.6689997F));
                    builder.AddCubicBezier(new Vector2(-43.1570015F, -11.6689997F), new Vector2(-43.0219994F, -11.7770004F), new Vector2(-42.7809982F, -11.9879999F));
                    builder.AddLine(new Vector2(-42.7290001F, -12.0159998F));
                    builder.AddCubicBezier(new Vector2(-41.8740005F, -12.7379999F), new Vector2(-39.7369995F, -14.3999996F), new Vector2(-36.644001F, -16.3239994F));
                    builder.AddLine(new Vector2(-36.4539986F, -16.427F));
                    builder.AddCubicBezier(new Vector2(-22.6560001F, -24.8250008F), new Vector2(9.71399975F, -37.2879982F), new Vector2(35.526001F, 8.67800045F));
                    builder.AddCubicBezier(new Vector2(42.2249985F, 20.6019993F), new Vector2(43.1570015F, 26.993F), new Vector2(40.3569984F, 29.559F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_17()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(56.3959999F, 34.8510017F));
                    builder.AddLine(new Vector2(24.2059994F, 57.5F));
                    builder.AddCubicBezier(new Vector2(24.2059994F, 57.5F), new Vector2(-21.8570004F, -34.855999F), new Vector2(-56.3959999F, -14.2930002F));
                    builder.AddLine(new Vector2(-26.7700005F, -35.1500015F));
                    builder.AddLine(new Vector2(-24.2360001F, -36.9389992F));
                    builder.AddCubicBezier(new Vector2(10.3299999F, -57.5F), new Vector2(56.3959999F, 34.8510017F), new Vector2(56.3959999F, 34.8510017F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_18()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(53.2330017F, 29.0100002F));
                    builder.AddLine(new Vector2(53.1780014F, 29.0389996F));
                    builder.AddLine(new Vector2(52.0299988F, 29.8400002F));
                    builder.AddLine(new Vector2(20.9400005F, 51.7919998F));
                    builder.AddCubicBezier(new Vector2(23.7399998F, 49.2260017F), new Vector2(22.8080006F, 42.8349991F), new Vector2(16.1049995F, 30.9109993F));
                    builder.AddCubicBezier(new Vector2(-9.70300007F, -15.0539999F), new Vector2(-42.0760002F, -2.59200001F), new Vector2(-55.875F, 5.80200005F));
                    builder.AddLine(new Vector2(-30.3840008F, -12.085F));
                    builder.AddCubicBezier(new Vector2(-30.3840008F, -12.085F), new Vector2(14.5570002F, -51.7910004F), new Vector2(48.2929993F, 8.26200008F));
                    builder.AddCubicBezier(new Vector2(54.8610001F, 19.9750004F), new Vector2(55.875F, 26.3369999F), new Vector2(53.2330017F, 29.0100002F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_19()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-129.024994F, 74.3499985F));
                    builder.AddLine(new Vector2(129.024994F, 223.052994F));
                    builder.AddLine(new Vector2(129.024994F, 168.360001F));
                    builder.AddLine(new Vector2(129.024994F, -74.3499985F));
                    builder.AddLine(new Vector2(-129.024994F, -223.052994F));
                    builder.AddLine(new Vector2(-129.024994F, 74.3499985F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_20()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-129.022995F, -74.3499985F));
                    builder.AddLine(new Vector2(-129.022995F, 223.052994F));
                    builder.AddLine(new Vector2(129.022995F, 74.3499985F));
                    builder.AddLine(new Vector2(129.022995F, -223.052994F));
                    builder.AddLine(new Vector2(-129.022995F, -74.3499985F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_21()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(-193.531998F, -65.8059998F));
                    builder.AddLine(new Vector2(64.5F, 82.8970032F));
                    builder.AddLine(new Vector2(193.531998F, 65.8059998F));
                    builder.AddLine(new Vector2(-64.5169983F, -82.8970032F));
                    builder.AddLine(new Vector2(-193.531998F, -65.8059998F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            CanvasGeometry Geometry_22()
            {
                CanvasGeometry result;
                using (var builder = new CanvasPathBuilder(null))
                {
                    builder.SetFilledRegionDetermination(CanvasFilledRegionDetermination.Winding);
                    builder.BeginFigure(new Vector2(63.0390015F, -110.68F));
                    builder.AddLine(new Vector2(195.003998F, -34.632F));
                    builder.AddLine(new Vector2(-68.9260025F, 110.68F));
                    builder.AddLine(new Vector2(-195.003998F, 38.0250015F));
                    builder.AddLine(new Vector2(63.0390015F, -110.68F));
                    builder.EndFigure(CanvasFigureLoop.Open);
                    result = CanvasGeometry.CreatePath(builder);
                }
                return result;
            }

            StepEasingFunction HoldThenStepEasingFunction()
            {
                var result = _holdThenStepEasingFunction = _c.CreateStepEasingFunction();
                result.IsFinalStepSingleFrame = true;
                return result;
            }

            // Layer (Shape): boxBack Outlines
            //   Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_00()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_00()));
                return result;
            }

            // Layer (Shape): boxBack Outlines
            //   Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_01()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_01()));
                return result;
            }

            // Layer (Shape): boxBack Outlines
            //   Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_02()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_02()));
                return result;
            }

            // Layer (Shape): boxBack Outlines
            //   Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_03()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_03()));
                return result;
            }

            // Layer (Shape): coin Outlines
            //   Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_04()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_04()));
                return result;
            }

            // Layer (Shape): coin Outlines
            //   Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_05()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_05()));
                return result;
            }

            CompositionPathGeometry PathGeometry_06()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_06()));
                return result;
            }

            // Layer (Shape): gift Outlines
            //   Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_07()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_07()));
                return result;
            }

            // Layer (Shape): gift Outlines
            //   Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_08()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_08()));
                return result;
            }

            // Layer (Shape): gift Outlines
            //   Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_09()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_09()));
                return result;
            }

            // Layer (Shape): gift Outlines
            //   Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_10()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_10()));
                return result;
            }

            // Layer (Shape): gift Outlines
            //   Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_11()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_11()));
                return result;
            }

            // Layer (Shape): gift Outlines
            //   Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_12()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_12()));
                return result;
            }

            // Layer (Shape): gift Outlines
            //   Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_13()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_13()));
                return result;
            }

            // Layer (Shape): gift Outlines
            //   Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_14()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_14()));
                return result;
            }

            // Layer (Shape): gift Outlines
            //   Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_15()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_15()));
                return result;
            }

            // Layer (Shape): gift Outlines
            //   Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_16()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_16()));
                return result;
            }

            // Layer (Shape): gift Outlines
            //   Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_17()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_17()));
                return result;
            }

            // Layer (Shape): gift Outlines
            //   Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_18()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_18()));
                return result;
            }

            // Layer (Shape): boxFront Outlines
            //   Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_19()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_19()));
                return result;
            }

            // Layer (Shape): boxFront Outlines
            //   Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_20()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_20()));
                return result;
            }

            // Layer (Shape): boxFront Outlines
            //   Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_21()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_21()));
                return result;
            }

            // Layer (Shape): boxFront Outlines
            //   Path 1
            // Path 1.PathGeometry
            CompositionPathGeometry PathGeometry_22()
            {
                var result = _c.CreatePathGeometry(new CompositionPath(Geometry_22()));
                return result;
            }

            // The root of the composition.
            ContainerVisual Root()
            {
                var result = _root = _c.CreateContainerVisual();
                var propertySet = result.Properties;
                propertySet.InsertScalar("Progress", 0);
                propertySet.InsertScalar("t0", 0);
                propertySet.InsertScalar("t1", 0);
                propertySet.InsertScalar("t2", 0);
                propertySet.InsertScalar("t3", 0);
                var children = result.Children;
                children.InsertAtTop(ShapeVisual());
                result.StartAnimation("t0", ScalarAnimation_0_to_1_0());
                var controller = result.TryGetAnimationController("t0");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                result.StartAnimation("t1", ScalarAnimation_0_to_1_1());
                controller = result.TryGetAnimationController("t1");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                result.StartAnimation("t2", ScalarAnimation_0_to_1_2());
                controller = result.TryGetAnimationController("t2");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                result.StartAnimation("t3", _scalarAnimation_0_to_1_0);
                controller = result.TryGetAnimationController("t3");
                controller.Pause();
                controller.StartAnimation("Progress", _scalarExpressionAnimation);
                return result;
            }

            ScalarKeyFrameAnimation ScalarAnimation_0_to_1_0()
            {
                var result = _scalarAnimation_0_to_1_0 = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0.442857236F, 0, _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.471428484F, 1, _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.471428573F, 0, _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.499999911F, 1, _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.528571546F, 0, _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.557142735F, 1, _cubicBezierEasingFunction_0);
                return result;
            }

            ScalarKeyFrameAnimation ScalarAnimation_0_to_1_1()
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0.157142967F, 0, _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.199999899F, 1, _cubicBezierEasingFunction_0);
                return result;
            }

            ScalarKeyFrameAnimation ScalarAnimation_0_to_1_2()
            {
                var result = _c.CreateScalarKeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0.314285815F, 0, _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.357142746F, 1, _cubicBezierEasingFunction_0);
                return result;
            }

            ExpressionAnimation ScalarExpressionAnimation()
            {
                var result = _scalarExpressionAnimation = _c.CreateExpressionAnimation();
                result.SetReferenceParameter("_", _root);
                result.Expression = "_.Progress";
                return result;
            }

            ShapeVisual ShapeVisual()
            {
                var result = _c.CreateShapeVisual();
                result.Size = new Vector2(1080, 1200);
                var shapes = result.Shapes;
                // Layer (Shape): boxBack Outlines
                shapes.Add(ContainerShape_0());
                // Layer (Shape): coin Outlines
                shapes.Add(ContainerShape_1());
                // Layer (Shape): gift Outlines
                shapes.Add(ContainerShape_2());
                // Layer (Shape): boxFront Outlines
                shapes.Add(ContainerShape_3());
                return result;
            }

            // Layer (Shape): boxBack Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_00()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 343.742004F, 236.535995F);
                result.FillBrush = ColorBrush_AlmostDarkSlateGray_FF404F51();
                result.Geometry = PathGeometry_00();
                return result;
            }

            // Layer (Shape): boxBack Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_01()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 214.934006F, 311.109985F);
                result.FillBrush = ColorBrush_AlmostDarkSlateGray_FF374346();
                result.Geometry = PathGeometry_01();
                return result;
            }

            // Layer (Shape): boxBack Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_02()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 171.996994F, 118.389999F);
                result.FillBrush = ColorBrush_AlmostSlateGray_FF6C8488();
                result.Geometry = PathGeometry_02();
                return result;
            }

            // Layer (Shape): boxBack Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_03()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 515.922974F, 159.341003F);
                result.FillBrush = ColorBrush_AlmostSlateGray_FF677C7E();
                result.Geometry = PathGeometry_03();
                return result;
            }

            // Layer (Shape): coin Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_04()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 94.6790009F, 108.216003F);
                result.FillBrush = ColorBrush_AlmostDarkKhaki_FFD2BE6A();
                result.Geometry = PathGeometry_04();
                return result;
            }

            // Layer (Shape): coin Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_05()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 78.1470032F, 115.390999F);
                result.FillBrush = ColorBrush_AlmostKhaki_FFF4E879();
                result.Geometry = PathGeometry_05();
                return result;
            }

            // Layer (Shape): coin Outlines
            CompositionSpriteShape SpriteShape_06()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 81.2929993F, 118.5F);
                result.FillBrush = ColorBrush_White();
                result.Geometry = PathGeometry_06();
                return result;
            }

            // Layer (Shape): gift Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_07()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 100.739998F, 290.161987F);
                result.FillBrush = ColorBrush_AlmostDarkSlateGray_FF2C4653();
                result.Geometry = PathGeometry_07();
                return result;
            }

            // Layer (Shape): gift Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_08()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 301.205994F, 290.162994F);
                result.FillBrush = ColorBrush_AlmostDarkSlateGray_FF2B3D51();
                result.Geometry = PathGeometry_08();
                return result;
            }

            // Layer (Shape): gift Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_09()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 201.227997F, 116.497002F);
                result.FillBrush = ColorBrush_AlmostDarkSlateGray_FF3D5A71();
                result.Geometry = PathGeometry_09();
                return result;
            }

            // Layer (Shape): gift Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_10()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 100.737999F, 290.164001F);
                result.FillBrush = ColorBrush_AlmostMediumSeaGreen_FF22A281();
                result.Geometry = PathGeometry_10();
                return result;
            }

            // Layer (Shape): gift Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_11()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 201.567993F, 116.130997F);
                result.FillBrush = ColorBrush_AlmostLightSeaGreen_FF23BC9C();
                result.Geometry = PathGeometry_11();
                return result;
            }

            // Layer (Shape): gift Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_12()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 301.175995F, 290.164001F);
                result.FillBrush = ColorBrush_AlmostDarkCyan_FF1E9579();
                result.Geometry = PathGeometry_12();
                return result;
            }

            // Layer (Shape): gift Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_13()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 201.567001F, 116.132004F);
                result.FillBrush = _colorBrush_AlmostLightSeaGreen_FF23BC9C;
                result.Geometry = PathGeometry_13();
                return result;
            }

            // Layer (Shape): gift Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_14()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 137.014008F, 34.4360008F);
                result.FillBrush = ColorBrush_AlmostDarkSlateGray_FF485A5E();
                result.Geometry = PathGeometry_14();
                return result;
            }

            // Layer (Shape): gift Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_15()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 129.378998F, 81.802002F);
                result.FillBrush = ColorBrush_AlmostDarkCyan_FF1F9B7C();
                result.Geometry = PathGeometry_15();
                return result;
            }

            // Layer (Shape): gift Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_16()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 229.876999F, 139.647995F);
                result.FillBrush = _colorBrush_AlmostDarkCyan_FF1F9B7C;
                result.Geometry = PathGeometry_16();
                return result;
            }

            // Layer (Shape): gift Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_17()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 162.516006F, 70.4800034F);
                result.FillBrush = _colorBrush_AlmostLightSeaGreen_FF23BC9C;
                result.Geometry = PathGeometry_17();
                return result;
            }

            // Layer (Shape): gift Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_18()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 249.294998F, 117.417F);
                result.FillBrush = _colorBrush_AlmostLightSeaGreen_FF23BC9C;
                result.Geometry = PathGeometry_18();
                return result;
            }

            // Layer (Shape): boxFront Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_19()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 258.290009F, 223.304001F);
                result.FillBrush = _colorBrush_AlmostDarkSlateGray_FF485A5E;
                result.Geometry = PathGeometry_19();
                return result;
            }

            // Layer (Shape): boxFront Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_20()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 516.336975F, 223.304993F);
                result.FillBrush = _colorBrush_AlmostDarkSlateGray_FF374346;
                result.Geometry = PathGeometry_20();
                return result;
            }

            // Layer (Shape): boxFront Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_21()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 193.781998F, 83.1480026F);
                result.FillBrush = _colorBrush_AlmostSlateGray_FF677C7E;
                result.Geometry = PathGeometry_21();
                return result;
            }

            // Layer (Shape): boxFront Outlines
            // Path 1
            CompositionSpriteShape SpriteShape_22()
            {
                var result = _c.CreateSpriteShape();
                result.TransformMatrix = new Matrix3x2(1, 0, 0, 1, 582.31897F, 110.931F);
                result.FillBrush = _colorBrush_AlmostSlateGray_FF6C8488;
                result.Geometry = PathGeometry_22();
                return result;
            }

            StepEasingFunction StepThenHoldEasingFunction()
            {
                var result = _stepThenHoldEasingFunction = _c.CreateStepEasingFunction();
                result.IsInitialStepSingleFrame = true;
                return result;
            }

            // Layer (Shape): boxBack Outlines
            // Position
            Vector2KeyFrameAnimation Vector2Animation_0()
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.SetReferenceParameter("_", _root);
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, new Vector2(540.01001F, 895.005005F), StepThenHoldEasingFunction());
                result.InsertKeyFrame(0.314285725F, new Vector2(540.01001F, 895.005005F), HoldThenStepEasingFunction());
                result.InsertKeyFrame(0.357142866F, new Vector2(540.01001F, 916.098999F), CubicBezierEasingFunction_0());
                result.InsertKeyFrame(0.400000006F, new Vector2(540.01001F, 895.005005F), _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.442857146F, new Vector2(540.01001F, 895.005005F), _cubicBezierEasingFunction_0);
                result.InsertExpressionKeyFrame(0.471428484F, "(Pow(1 - _.t0, 3) * Vector2(540.01,895.005)) + (3 * Square(1 - _.t0) * _.t0 * Vector2(541.5725,895.005)) + (3 * (1 - _.t0) * Square(_.t0) * Vector2(549.7756,895.005)) + (Pow(_.t0, 3) * Vector2(549.385,895.005))", _stepThenHoldEasingFunction);
                result.InsertExpressionKeyFrame(0.499999911F, "(Pow(1 - _.t0, 3) * Vector2(549.385,895.005)) + (3 * Square(1 - _.t0) * _.t0 * Vector2(548.9944,895.005)) + (3 * (1 - _.t0) * Square(_.t0) * Vector2(536.8848,895.005)) + (Pow(_.t0, 3) * Vector2(537.666,895.005))", _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.5F, new Vector2(537.666016F, 895.005005F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.528571427F, new Vector2(554.072021F, 895.005005F), _cubicBezierEasingFunction_0);
                result.InsertExpressionKeyFrame(0.557142735F, "(Pow(1 - _.t0, 3) * Vector2(554.072,895.005)) + (3 * Square(1 - _.t0) * _.t0 * Vector2(554.4626,895.005)) + (3 * (1 - _.t0) * Square(_.t0) * Vector2(542.3538,895.005)) + (Pow(_.t0, 3) * Vector2(540.01,895.005))", _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.557142854F, new Vector2(540.01001F, 895.005005F), _stepThenHoldEasingFunction);
                return result;
            }

            // Layer (Shape): coin Outlines
            // Position
            Vector2KeyFrameAnimation Vector2Animation_1()
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.SetReferenceParameter("_", _root);
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, new Vector2(538.924988F, 399.328003F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.0714285746F, new Vector2(538.924988F, 399.328003F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.157142863F, new Vector2(538.924988F, 399.328003F), _holdThenStepEasingFunction);
                result.InsertExpressionKeyFrame(0.199999899F, "(Pow(1 - _.t1, 3) * Vector2(538.925,399.328)) + (3 * Square(1 - _.t1) * _.t1 * Vector2(538.925,418.5362)) + (3 * (1 - _.t1) * Square(_.t1) * Vector2(538.925,324.5087)) + (Pow(_.t1, 3) * Vector2(538.925,361.496))", _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.200000003F, new Vector2(538.924988F, 361.496002F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.314285725F, new Vector2(538.924988F, 1060.26599F), CubicBezierEasingFunction_1());
                return result;
            }

            // Layer (Shape): coin Outlines
            // Scale
            Vector2KeyFrameAnimation Vector2Animation_2()
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, new Vector2(0, 0), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.0535714291F, new Vector2(1, 1), _cubicBezierEasingFunction_0);
                return result;
            }

            // Layer (Shape): gift Outlines
            // Position
            Vector2KeyFrameAnimation Vector2Animation_3()
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.SetReferenceParameter("_", _root);
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, new Vector2(539.692017F, 1032.44299F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.314285725F, new Vector2(539.692017F, 1032.44299F), _holdThenStepEasingFunction);
                result.InsertExpressionKeyFrame(0.357142746F, "(Pow(1 - _.t2, 3) * Vector2(539.692,1032.443)) + (3 * Square(1 - _.t2) * _.t2 * Vector2(539.692,1032.443)) + (3 * (1 - _.t2) * Square(_.t2) * Vector2(539.692,1059.397)) + (Pow(_.t2, 3) * Vector2(539.692,1048.068))", _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.357142836F, new Vector2(539.692017F, 1048.06799F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.485714287F, new Vector2(539.692017F, 1020.72498F), _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.54285717F, new Vector2(539.692017F, 919.942993F), _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.628571451F, new Vector2(539.692017F, 694.942993F), _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.671428561F, new Vector2(539.692017F, 720.724976F), _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.814285696F, new Vector2(539.692017F, 720.724976F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.857142866F, new Vector2(539.692017F, 680.880981F), _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.928571403F, new Vector2(539.692017F, 919.942993F), _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.982142866F, new Vector2(539.692017F, 1020.72498F), _cubicBezierEasingFunction_0);
                return result;
            }

            // Layer (Shape): gift Outlines
            // Scale
            Vector2KeyFrameAnimation Vector2Animation_4()
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, new Vector2(0.620000005F, 0.620000005F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.485714287F, new Vector2(0.620000005F, 0.620000005F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.54285717F, new Vector2(1, 1), _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.928571403F, new Vector2(1, 1), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.982142866F, new Vector2(0.620000005F, 0.620000005F), _cubicBezierEasingFunction_0);
                return result;
            }

            // Layer (Shape): boxFront Outlines
            // Position
            Vector2KeyFrameAnimation Vector2Animation_5()
            {
                var result = _c.CreateVector2KeyFrameAnimation();
                result.SetReferenceParameter("_", _root);
                result.Duration = TimeSpan.FromTicks(c_durationTicks);
                result.InsertKeyFrame(0, new Vector2(542.405029F, 882.914978F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.314285725F, new Vector2(542.405029F, 882.914978F), _holdThenStepEasingFunction);
                result.InsertKeyFrame(0.357142866F, new Vector2(542.405029F, 904.008972F), _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.400000006F, new Vector2(542.405029F, 882.914978F), _cubicBezierEasingFunction_0);
                result.InsertKeyFrame(0.442857146F, new Vector2(542.405029F, 882.914978F), _cubicBezierEasingFunction_0);
                result.InsertExpressionKeyFrame(0.471428484F, "(Pow(1 - _.t3, 3) * Vector2(542.405,882.915)) + (3 * Square(1 - _.t3) * _.t3 * Vector2(543.9675,882.915)) + (3 * (1 - _.t3) * Square(_.t3) * Vector2(552.1707,882.915)) + (Pow(_.t3, 3) * Vector2(551.78,882.915))", _stepThenHoldEasingFunction);
                result.InsertExpressionKeyFrame(0.499999911F, "(Pow(1 - _.t3, 3) * Vector2(551.78,882.915)) + (3 * Square(1 - _.t3) * _.t3 * Vector2(551.3894,882.915)) + (3 * (1 - _.t3) * Square(_.t3) * Vector2(539.2797,882.915)) + (Pow(_.t3, 3) * Vector2(540.061,882.915))", _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.5F, new Vector2(540.060974F, 882.914978F), _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.528571427F, new Vector2(556.46698F, 882.914978F), _cubicBezierEasingFunction_0);
                result.InsertExpressionKeyFrame(0.557142735F, "(Pow(1 - _.t3, 3) * Vector2(556.467,882.915)) + (3 * Square(1 - _.t3) * _.t3 * Vector2(556.8576,882.915)) + (3 * (1 - _.t3) * Square(_.t3) * Vector2(544.7488,882.915)) + (Pow(_.t3, 3) * Vector2(542.405,882.915))", _stepThenHoldEasingFunction);
                result.InsertKeyFrame(0.557142854F, new Vector2(542.405029F, 882.914978F), _stepThenHoldEasingFunction);
                return result;
            }

            internal AnimatedVisual(Compositor compositor)
            {
                _c = compositor;
                _reusableExpressionAnimation = compositor.CreateExpressionAnimation();
                Root();
            }

            Visual IAnimatedVisual.RootVisual => _root;
            TimeSpan IAnimatedVisual.Duration => TimeSpan.FromTicks(c_durationTicks);
            Vector2 IAnimatedVisual.Size => new Vector2(1080, 1200);
            void IDisposable.Dispose() => _root?.Dispose();
        }
    }
}
