// ******************************************************************
// Copyright (c) Microsoft. All rights reserved.
// This code is licensed under the MIT License (MIT).
// THE CODE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
// INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH
// THE CODE OR THE USE OR OTHER DEALINGS IN THE CODE.
// ******************************************************************

namespace Microsoft.Toolkit.Uwp.UI.Animations.Expressions
{
    internal enum ExpressionNodeType
    {
        ConstantValue,
        ConstantParameter,
        CurrentValueProperty,
        Reference,
        ReferenceProperty,
        StartingValueProperty,
        TargetReference,
        Conditional,
        Swizzle,
        Add,
        And,
        Divide,
        Equals,
        GreaterThan,
        GreaterThanEquals,
        LessThan,
        LessThanEquals,
        Multiply,
        Not,
        NotEquals,
        Or,
        Subtract,
        Absolute,
        Acos,
        Asin,
        Atan,
        Cos,
        Ceil,
        Clamp,
        ColorHsl,
        ColorRgb,
        ColorLerp,
        ColorLerpHsl,
        ColorLerpRgb,
        Concatenate,
        Distance,
        DistanceSquared,
        Floor,
        Inverse,
        Length,
        LengthSquared,
        Lerp,
        Ln,
        Log10,
        Max,
        Matrix3x2FromRotation,
        Matrix3x2FromScale,
        Matrix3x2FromSkew,
        Matrix3x2FromTranslation,
        Matrix3x2,
        Matrix4x4FromAxisAngle,
        Matrix4x4FromScale,
        Matrix4x4FromTranslation,
        Matrix4x4,
        Min,
        Modulus,
        Negate,
        Normalize,
        Pow,
        QuaternionFromAxisAngle,
        Quaternion,
        Round,
        Scale,
        Sin,
        Slerp,
        Sqrt,
        Square,
        Tan,
        ToDegrees,
        ToRadians,
        Transform,
        Vector2,
        Vector3,
        Vector4,

        Count
    }
}
