//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Toolkit.Win32.UI.Controls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DesignerUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DesignerUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Toolkit.Win32.UI.Controls.DesignerUI", typeof(DesignerUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility.
        /// </summary>
        internal static string CatAccessibility {
            get {
                return ResourceManager.GetString("CatAccessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string CatAction {
            get {
                return ResourceManager.GetString("CatAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string CatAppearance {
            get {
                return ResourceManager.GetString("CatAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        internal static string CatBehavior {
            get {
                return ResourceManager.GetString("CatBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string CatData {
            get {
                return ResourceManager.GetString("CatData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string CatDisplay {
            get {
                return ResourceManager.GetString("CatDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag Drop.
        /// </summary>
        internal static string CatDragDrop {
            get {
                return ResourceManager.GetString("CatDragDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus.
        /// </summary>
        internal static string CatFocus {
            get {
                return ResourceManager.GetString("CatFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string CatItems {
            get {
                return ResourceManager.GetString("CatItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string CatLayout {
            get {
                return ResourceManager.GetString("CatLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string CatSettings {
            get {
                return ResourceManager.GetString("CatSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code in your application is attempting to set a property of the WebView control that is read-only because the control has already begun initializing. Your code can modify this property before it calls the ISupportInitialize.BeginInit method, but not after..
        /// </summary>
        internal static string E_CANNOT_CHANGE_AFTER_INIT {
            get {
                return ResourceManager.GetString("E_CANNOT_CHANGE_AFTER_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize a WebView control in a ClickOnce application. See Release notes: https://go.microsoft.com/fwlink/?linkid=872619.
        /// </summary>
        internal static string E_CLICKONCE_PARTIAL_TRUST {
            get {
                return ResourceManager.GetString("E_CLICKONCE_PARTIAL_TRUST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize the WebView control because the system is running a version of Windows that doesn’t support this control. The WebView control runs only on Windows 10 April 2018 Update or later..
        /// </summary>
        internal static string E_NOTSUPPORTED_OS_RS4 {
            get {
                return ResourceManager.GetString("E_NOTSUPPORTED_OS_RS4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The system is running a version of Windows that doesn&apos;t support this control..
        /// </summary>
        internal static string E_UNRECOGNIZED_OS {
            get {
                return ResourceManager.GetString("E_UNRECOGNIZED_OS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize the WebView control because the Microsoft Edge web browser has been disabled by the group or location admin policy of your system..
        /// </summary>
        internal static string E_WEB_BROWSER_DISABLED {
            get {
                return ResourceManager.GetString("E_WEB_BROWSER_DISABLED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize a WebView control in a ClickOnce application or from an application that is opened in certain types of Web browsers. See Release notes: https://go.microsoft.com/fwlink/?linkid=872619.
        /// </summary>
        internal static string E_WEB_PERMISSION_RESTRICTED {
            get {
                return ResourceManager.GetString("E_WEB_PERMISSION_RESTRICTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code in your application is attempting to initialize a WebView control that is already initialized..
        /// </summary>
        internal static string E_WEBVIEW_ALREADY_INITIALIZED {
            get {
                return ResourceManager.GetString("E_WEBVIEW_ALREADY_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code in your application is attempting to initialize a WebView control that is already in the process of being initialized by a previous call to the ISupportInitialize.BeginInit() method..
        /// </summary>
        internal static string E_WEBVIEW_ALREADY_INITIALIZING {
            get {
                return ResourceManager.GetString("E_WEBVIEW_ALREADY_INITIALIZING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code in your application is attempting to use a member of the WebView control before the control is completely initialized..
        /// </summary>
        internal static string E_WEBVIEW_CANNOT_INVOKE_BEFORE_INIT {
            get {
                return ResourceManager.GetString("E_WEBVIEW_CANNOT_INVOKE_BEFORE_INIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code in your application sets the Source property or calls the Navigate method by using an invalid URI..
        /// </summary>
        internal static string E_WEBVIEW_INVALID_URI {
            get {
                return ResourceManager.GetString("E_WEBVIEW_INVALID_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The code in your application sets the Source property or calls the Navigate method by using a URI that doesn’t have the format of an absolute URI..
        /// </summary>
        internal static string E_WEBVIEW_NOT_ABSOLUTE_URI {
            get {
                return ResourceManager.GetString("E_WEBVIEW_NOT_ABSOLUTE_URI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The WebView control is not initialized..
        /// </summary>
        internal static string E_WEBVIEW_NOT_INITIALIZED {
            get {
                return ResourceManager.GetString("E_WEBVIEW_NOT_INITIALIZED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize the WebView control because the code in your application calls the IsSupportInitialize.EndInit() method without first calling the ISupportInitialize.BeginInit() method.
        /// </summary>
        internal static string E_WEBVIEW_NOT_INITIALIZING {
            get {
                return ResourceManager.GetString("E_WEBVIEW_NOT_INITIALIZING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the status of WebView contains a full screen element..
        /// </summary>
        internal static string WebViewContainsFullScreenElementChangedDesc {
            get {
                return ResourceManager.GetString("WebViewContainsFullScreenElementChangedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when WebView started loading new content..
        /// </summary>
        internal static string WebViewContentLoadingDesc {
            get {
                return ResourceManager.GetString("WebViewContentLoadingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Embeds a view into your application that renders web content using the Microsoft Edge rendering engine..
        /// </summary>
        internal static string WebViewDesc {
            get {
                return ResourceManager.GetString("WebViewDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when WebView finished parsing the current content..
        /// </summary>
        internal static string WebViewDomContentLoadedDesc {
            get {
                return ResourceManager.GetString("WebViewDomContentLoadedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the enterprise ID of this process..
        /// </summary>
        internal static string WebViewEnterpriseIdDesc {
            get {
                return ResourceManager.GetString("WebViewEnterpriseIdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when a frame in WebView has started loading new content..
        /// </summary>
        internal static string WebViewFrameContentLoadingDesc {
            get {
                return ResourceManager.GetString("WebViewFrameContentLoadingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when a frame in WebView finished parsing the current content..
        /// </summary>
        internal static string WebViewFrameDomContentLoadedDesc {
            get {
                return ResourceManager.GetString("WebViewFrameDomContentLoadedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when a frame in WebView finished navigating to new content..
        /// </summary>
        internal static string WebViewFrameNavigationCompletedDesc {
            get {
                return ResourceManager.GetString("WebViewFrameNavigationCompletedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs before a frame in WebView navigates to new content..
        /// </summary>
        internal static string WebViewFrameNavigationStartingDesc {
            get {
                return ResourceManager.GetString("WebViewFrameNavigationStartingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs periodically while WebView executes JavaScript, letting you halt the script..
        /// </summary>
        internal static string WebViewLongRunningScriptDetectedDesc {
            get {
                return ResourceManager.GetString("WebViewLongRunningScriptDetectedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when a focus move is requested..
        /// </summary>
        internal static string WebViewMoveFocusRequestedDesc {
            get {
                return ResourceManager.GetString("WebViewMoveFocusRequestedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when WebView finished navigating to new content..
        /// </summary>
        internal static string WebViewNavigationCompletedDesc {
            get {
                return ResourceManager.GetString("WebViewNavigationCompletedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs before WebView navigates to new content..
        /// </summary>
        internal static string WebViewNavigationStartingDesc {
            get {
                return ResourceManager.GetString("WebViewNavigationStartingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when an action is performed that causes content to be opened in a new window..
        /// </summary>
        internal static string WebViewNewWindowRequestedDesc {
            get {
                return ResourceManager.GetString("WebViewNewWindowRequestedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when WebView requires a permission..
        /// </summary>
        internal static string WebViewPermissionRequestedDesc {
            get {
                return ResourceManager.GetString("WebViewPermissionRequestedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when content in WebView passes a string from JavaScript..
        /// </summary>
        internal static string WebViewScriptNotifyDesc {
            get {
                return ResourceManager.GetString("WebViewScriptNotifyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the Uniform Resource Identifier (URI) source of the content to display..
        /// </summary>
        internal static string WebViewSourceDesc {
            get {
                return ResourceManager.GetString("WebViewSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when WebView shows a warning page for content that was reported as unsafe by SmartScreen filter..
        /// </summary>
        internal static string WebViewUnsafeContentWarningDisplayingDesc {
            get {
                return ResourceManager.GetString("WebViewUnsafeContentWarningDisplayingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when an attempt is made to navigate to a Source using a scheme that WebView does not support..
        /// </summary>
        internal static string WebViewUnsupportedUriSchemeIdentifiedDesc {
            get {
                return ResourceManager.GetString("WebViewUnsupportedUriSchemeIdentifiedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when WebView attempts to download an unsupported file..
        /// </summary>
        internal static string WebViewUnviewableContentIdentifiedDesc {
            get {
                return ResourceManager.GetString("WebViewUnviewableContentIdentifiedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when WebView requests a HTTP resource..
        /// </summary>
        internal static string WebViewWebResourceRequestedDesc {
            get {
                return ResourceManager.GetString("WebViewWebResourceRequestedDesc", resourceCulture);
            }
        }
    }
}
