//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Toolkit.Win32.UI.Controls {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DesignerUI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DesignerUI() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Toolkit.Win32.UI.Controls.DesignerUI", typeof(DesignerUI).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessibility.
        /// </summary>
        internal static string CatAccessibility {
            get {
                return ResourceManager.GetString("CatAccessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        internal static string CatAction {
            get {
                return ResourceManager.GetString("CatAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string CatAppearance {
            get {
                return ResourceManager.GetString("CatAppearance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Behavior.
        /// </summary>
        internal static string CatBehavior {
            get {
                return ResourceManager.GetString("CatBehavior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string CatData {
            get {
                return ResourceManager.GetString("CatData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display.
        /// </summary>
        internal static string CatDisplay {
            get {
                return ResourceManager.GetString("CatDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drag Drop.
        /// </summary>
        internal static string CatDragDrop {
            get {
                return ResourceManager.GetString("CatDragDrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Focus.
        /// </summary>
        internal static string CatFocus {
            get {
                return ResourceManager.GetString("CatFocus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string CatItems {
            get {
                return ResourceManager.GetString("CatItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string CatLayout {
            get {
                return ResourceManager.GetString("CatLayout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string CatSettings {
            get {
                return ResourceManager.GetString("CatSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value cannot be changed once the WebView has been initialized..
        /// </summary>
        internal static string InvalidOp_Immutable {
            get {
                return ResourceManager.GetString("InvalidOp_Immutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WebView is only supported on Windows 10 and Redstone 4 or later..
        /// </summary>
        internal static string NotSup_Win10RS4 {
            get {
                return ResourceManager.GetString("NotSup_Win10RS4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when the status of WebView contains a full screen element..
        /// </summary>
        internal static string WebViewContainsFullScreenElementChangedDesc {
            get {
                return ResourceManager.GetString("WebViewContainsFullScreenElementChangedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when WebView started loading new content..
        /// </summary>
        internal static string WebViewContentLoadingDesc {
            get {
                return ResourceManager.GetString("WebViewContentLoadingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when WebView finished parsing the current content..
        /// </summary>
        internal static string WebViewDomContentLoadedDesc {
            get {
                return ResourceManager.GetString("WebViewDomContentLoadedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the enterprise ID of this process..
        /// </summary>
        internal static string WebViewEnterpriseIdDesc {
            get {
                return ResourceManager.GetString("WebViewEnterpriseIdDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when a frame in WebView has started loading new content..
        /// </summary>
        internal static string WebViewFrameContentLoadingDesc {
            get {
                return ResourceManager.GetString("WebViewFrameContentLoadingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when a frame in WebView finished parsing the current content..
        /// </summary>
        internal static string WebViewFrameDomContentLoadedDesc {
            get {
                return ResourceManager.GetString("WebViewFrameDomContentLoadedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when a frame in WebView finished navigating to new content..
        /// </summary>
        internal static string WebViewFrameNavigationCompletedDesc {
            get {
                return ResourceManager.GetString("WebViewFrameNavigationCompletedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs before a frame in WebView navigates to new content..
        /// </summary>
        internal static string WebViewFrameNavigationStartingDesc {
            get {
                return ResourceManager.GetString("WebViewFrameNavigationStartingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs periodically while WebView executes JavaScript, letting you halt the script..
        /// </summary>
        internal static string WebViewLongRunningScriptDetectedDesc {
            get {
                return ResourceManager.GetString("WebViewLongRunningScriptDetectedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when a focus move is requested..
        /// </summary>
        internal static string WebViewMoveFocusRequestedDesc {
            get {
                return ResourceManager.GetString("WebViewMoveFocusRequestedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when WebView finished navigating to new content..
        /// </summary>
        internal static string WebViewNavigationCompletedDesc {
            get {
                return ResourceManager.GetString("WebViewNavigationCompletedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs before WebView navigates to new content..
        /// </summary>
        internal static string WebViewNavigationStartingDesc {
            get {
                return ResourceManager.GetString("WebViewNavigationStartingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when an action is performed that causes content to be opened in a new window..
        /// </summary>
        internal static string WebViewNewWindowRequestedDesc {
            get {
                return ResourceManager.GetString("WebViewNewWindowRequestedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when WebView requires a permission..
        /// </summary>
        internal static string WebViewPermissionRequestedDesc {
            get {
                return ResourceManager.GetString("WebViewPermissionRequestedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when content in WebView passes a string from JavaScript..
        /// </summary>
        internal static string WebViewScriptNotifyDesc {
            get {
                return ResourceManager.GetString("WebViewScriptNotifyDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gets or sets the Uniform Resource Identifier (URI) source of the content to display..
        /// </summary>
        internal static string WebViewSourceDesc {
            get {
                return ResourceManager.GetString("WebViewSourceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when WebView shows a warning page for content that was reported as unsafe by SmartScreen filter..
        /// </summary>
        internal static string WebViewUnsafeContentWarningDisplayingDesc {
            get {
                return ResourceManager.GetString("WebViewUnsafeContentWarningDisplayingDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when an attempt is made to navigate to a Source using a scheme that WebView does not support..
        /// </summary>
        internal static string WebViewUnsupportedUriSchemeIdentifiedDesc {
            get {
                return ResourceManager.GetString("WebViewUnsupportedUriSchemeIdentifiedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when WebView attempts to download an unsupported file..
        /// </summary>
        internal static string WebViewUnviewableContentIdentifiedDesc {
            get {
                return ResourceManager.GetString("WebViewUnviewableContentIdentifiedDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occurs when WebView requests a HTTP resource..
        /// </summary>
        internal static string WebViewWebResourceRequestedDesc {
            get {
                return ResourceManager.GetString("WebViewWebResourceRequestedDesc", resourceCulture);
            }
        }
    }
}
