// ******************************************************************
// Copyright (c) Microsoft. All rights reserved.
// This code is licensed under the MIT License (MIT).
// THE CODE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED,
// INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
// FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
// IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM,
// DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT,
// TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH
// THE CODE OR THE USE OR OTHER DEALINGS IN THE CODE.
// ******************************************************************

using System.Globalization;
using System.Linq;

namespace Microsoft.Toolkit.Uwp.UI.Helpers.Emoji
{
    /// <summary>
    ///     Class to help manage use of Emojis
    /// </summary>
    public static class EmojiManager
    {
        private static readonly EmojiDetails[] EmojiArray =
        {
            new EmojiDetails(Emoji.HelmetWithWhiteCross, new[] { 0x26D1, 0xFE0F }, true), new EmojiDetails(Emoji.Kiss, new[] { 0x1F48F }, true), new EmojiDetails(Emoji.CoupleWithHeart, new[] { 0x1F491 }, true),
            new EmojiDetails(Emoji.Skier, new[] { 0x26F7, 0xFE0F }, true), new EmojiDetails(Emoji.GrinningFace, new[] { 0x1F600 }), new EmojiDetails(Emoji.GrinningFaceWithSmilingEyes, new[] { 0x1F601 }), new EmojiDetails(Emoji.FaceWithTearsOfJoy, new[] { 0x1F602 }),
            new EmojiDetails(Emoji.RollingOnTheFloorLaughing, new[] { 0x1F923 }), new EmojiDetails(Emoji.SmilingFaceWithOpenMouth, new[] { 0x1F603 }), new EmojiDetails(Emoji.SmilingFaceWithOpenMouthAndSmilingEyes, new[] { 0x1F604 }),
            new EmojiDetails(Emoji.SmilingFaceWithOpenMouthAndColdSweat, new[] { 0x1F605 }), new EmojiDetails(Emoji.SmilingFaceWithOpenMouthAndTightlyClosedEyes, new[] { 0x1F606 }), new EmojiDetails(Emoji.WinkingFace, new[] { 0x1F609 }), new EmojiDetails(Emoji.SmilingFaceWithSmilingEyes, new[] { 0x1F60A }),
            new EmojiDetails(Emoji.FaceSavouringDeliciousFood, new[] { 0x1F60B }), new EmojiDetails(Emoji.SmilingFaceWithSunglasses, new[] { 0x1F60E }), new EmojiDetails(Emoji.SmilingFaceWithHeartShapedEyes, new[] { 0x1F60D }), new EmojiDetails(Emoji.FaceThrowingAKiss, new[] { 0x1F618 }),
            new EmojiDetails(Emoji.KissingFace, new[] { 0x1F617 }), new EmojiDetails(Emoji.KissingFaceWithSmilingEyes, new[] { 0x1F619 }), new EmojiDetails(Emoji.KissingFaceWithClosedEyes, new[] { 0x1F61A }), new EmojiDetails(Emoji.WhiteSmilingFace, new[] { 0x263A, 0xFE0F }),
            new EmojiDetails(Emoji.SlightlySmilingFace, new[] { 0x1F642 }), new EmojiDetails(Emoji.HuggingFace, new[] { 0x1F917 }), new EmojiDetails(Emoji.ThinkingFace, new[] { 0x1F914 }), new EmojiDetails(Emoji.NeutralFace, new[] { 0x1F610 }), new EmojiDetails(Emoji.ExpressionlessFace, new[] { 0x1F611 }),
            new EmojiDetails(Emoji.FaceWithoutMouth, new[] { 0x1F636 }), new EmojiDetails(Emoji.FaceWithRollingEyes, new[] { 0x1F644 }), new EmojiDetails(Emoji.SmirkingFace, new[] { 0x1F60F }), new EmojiDetails(Emoji.PerseveringFace, new[] { 0x1F623 }),
            new EmojiDetails(Emoji.DisappointedButRelievedFace, new[] { 0x1F625 }), new EmojiDetails(Emoji.FaceWithOpenMouth, new[] { 0x1F62E }), new EmojiDetails(Emoji.ZipperMouthFace, new[] { 0x1F910 }), new EmojiDetails(Emoji.HushedFace, new[] { 0x1F62F }),
            new EmojiDetails(Emoji.SleepyFace, new[] { 0x1F62A }), new EmojiDetails(Emoji.TiredFace, new[] { 0x1F62B }), new EmojiDetails(Emoji.SleepingFace, new[] { 0x1F634 }), new EmojiDetails(Emoji.RelievedFace, new[] { 0x1F60C }), new EmojiDetails(Emoji.NerdFace, new[] { 0x1F913 }),
            new EmojiDetails(Emoji.FaceWithStuckOutTongue, new[] { 0x1F61B }), new EmojiDetails(Emoji.FaceWithStuckOutTongueAndWinkingEye, new[] { 0x1F61C }), new EmojiDetails(Emoji.FaceWithStuckOutTongueAndTightlyClosedEyes, new[] { 0x1F61D }), new EmojiDetails(Emoji.DroolingFace, new[] { 0x1F924 }),
            new EmojiDetails(Emoji.UnamusedFace, new[] { 0x1F612 }), new EmojiDetails(Emoji.FaceWithColdSweat, new[] { 0x1F613 }), new EmojiDetails(Emoji.PensiveFace, new[] { 0x1F614 }), new EmojiDetails(Emoji.ConfusedFace, new[] { 0x1F615 }), new EmojiDetails(Emoji.UpsideDownFace, new[] { 0x1F643 }),
            new EmojiDetails(Emoji.MoneyMouthFace, new[] { 0x1F911 }), new EmojiDetails(Emoji.AstonishedFace, new[] { 0x1F632 }), new EmojiDetails(Emoji.WhiteFrowningFace, new[] { 0x2639, 0xFE0F }), new EmojiDetails(Emoji.SlightlyFrowningFace, new[] { 0x1F641 }),
            new EmojiDetails(Emoji.ConfoundedFace, new[] { 0x1F616 }), new EmojiDetails(Emoji.DisappointedFace, new[] { 0x1F61E }), new EmojiDetails(Emoji.WorriedFace, new[] { 0x1F61F }), new EmojiDetails(Emoji.FaceWithLookOfTriumph, new[] { 0x1F624 }), new EmojiDetails(Emoji.CryingFace, new[] { 0x1F622 }),
            new EmojiDetails(Emoji.LoudlyCryingFace, new[] { 0x1F62D }), new EmojiDetails(Emoji.FrowningFaceWithOpenMouth, new[] { 0x1F626 }), new EmojiDetails(Emoji.AnguishedFace, new[] { 0x1F627 }), new EmojiDetails(Emoji.FearfulFace, new[] { 0x1F628 }), new EmojiDetails(Emoji.WearyFace, new[] { 0x1F629 }),
            new EmojiDetails(Emoji.GrimacingFace, new[] { 0x1F62C }), new EmojiDetails(Emoji.FaceWithOpenMouthAndColdSweat, new[] { 0x1F630 }), new EmojiDetails(Emoji.FaceScreamingInFear, new[] { 0x1F631 }), new EmojiDetails(Emoji.FlushedFace, new[] { 0x1F633 }),
            new EmojiDetails(Emoji.DizzyFace, new[] { 0x1F635 }), new EmojiDetails(Emoji.PoutingFace, new[] { 0x1F621 }), new EmojiDetails(Emoji.AngryFace, new[] { 0x1F620 }), new EmojiDetails(Emoji.FaceWithMedicalMask, new[] { 0x1F637 }), new EmojiDetails(Emoji.FaceWithThermometer, new[] { 0x1F912 }),
            new EmojiDetails(Emoji.FaceWithHeadBandage, new[] { 0x1F915 }), new EmojiDetails(Emoji.NauseatedFace, new[] { 0x1F922 }), new EmojiDetails(Emoji.SneezingFace, new[] { 0x1F927 }), new EmojiDetails(Emoji.SmilingFaceWithHalo, new[] { 0x1F607 }),
            new EmojiDetails(Emoji.FaceWithCowboyHat, new[] { 0x1F920 }), new EmojiDetails(Emoji.ClownFace, new[] { 0x1F921 }), new EmojiDetails(Emoji.LyingFace, new[] { 0x1F925 }), new EmojiDetails(Emoji.SmilingFaceWithHorns, new[] { 0x1F608 }), new EmojiDetails(Emoji.Imp, new[] { 0x1F47F }),
            new EmojiDetails(Emoji.JapaneseOgre, new[] { 0x1F479 }), new EmojiDetails(Emoji.JapaneseGoblin, new[] { 0x1F47A }), new EmojiDetails(Emoji.Skull, new[] { 0x1F480 }), new EmojiDetails(Emoji.SkullAndCrossbones, new[] { 0x2620, 0xFE0F }), new EmojiDetails(Emoji.Ghost, new[] { 0x1F47B }),
            new EmojiDetails(Emoji.ExtraterrestrialAlien, new[] { 0x1F47D }), new EmojiDetails(Emoji.AlienMonster, new[] { 0x1F47E }), new EmojiDetails(Emoji.RobotFace, new[] { 0x1F916 }), new EmojiDetails(Emoji.PileOfPoo, new[] { 0x1F4A9 }),
            new EmojiDetails(Emoji.SmilingCatFaceWithOpenMouth, new[] { 0x1F63A }), new EmojiDetails(Emoji.GrinningCatFaceWithSmilingEyes, new[] { 0x1F638 }), new EmojiDetails(Emoji.CatFaceWithTearsOfJoy, new[] { 0x1F639 }), new EmojiDetails(Emoji.SmilingCatFaceWithHeartShapedEyes, new[] { 0x1F63B }),
            new EmojiDetails(Emoji.CatFaceWithWrySmile, new[] { 0x1F63C }), new EmojiDetails(Emoji.KissingCatFaceWithClosedEyes, new[] { 0x1F63D }), new EmojiDetails(Emoji.WearyCatFace, new[] { 0x1F640 }), new EmojiDetails(Emoji.CryingCatFace, new[] { 0x1F63F }),
            new EmojiDetails(Emoji.PoutingCatFace, new[] { 0x1F63E }), new EmojiDetails(Emoji.SeeNoEvilMonkey, new[] { 0x1F648 }), new EmojiDetails(Emoji.HearNoEvilMonkey, new[] { 0x1F649 }), new EmojiDetails(Emoji.SpeakNoEvilMonkey, new[] { 0x1F64A }), new EmojiDetails(Emoji.Baby, new[] { 0x1F476 }, true),
            new EmojiDetails(Emoji.Boy, new[] { 0x1F466 }, true), new EmojiDetails(Emoji.Girl, new[] { 0x1F467 }, true), new EmojiDetails(Emoji.Man, new[] { 0x1F468 }, true), new EmojiDetails(Emoji.Woman, new[] { 0x1F469 }, true), new EmojiDetails(Emoji.OlderMan, new[] { 0x1F474 }, true),
            new EmojiDetails(Emoji.OlderWoman, new[] { 0x1F475 }, true), new EmojiDetails(Emoji.SleuthOrSpy, new[] { 0x1F575, 0xFE0F }, true), new EmojiDetails(Emoji.PoliceOfficer, new[] { 0x1F46E }, true), new EmojiDetails(Emoji.Guardsman, new[] { 0x1F482 }, true),
            new EmojiDetails(Emoji.ConstructionWorker, new[] { 0x1F477 }, true), new EmojiDetails(Emoji.Prince, new[] { 0x1F934 }, true), new EmojiDetails(Emoji.Princess, new[] { 0x1F478 }, true), new EmojiDetails(Emoji.ManWithTurban, new[] { 0x1F473 }, true),
            new EmojiDetails(Emoji.ManWithGuaPiMao, new[] { 0x1F472 }, true), new EmojiDetails(Emoji.PersonWithBlondHair, new[] { 0x1F471 }, true), new EmojiDetails(Emoji.ManInTuxedo, new[] { 0x1F935 }, true), new EmojiDetails(Emoji.BrideWithVeil, new[] { 0x1F470 }, true),
            new EmojiDetails(Emoji.PregnantWoman, new[] { 0x1F930 }, true), new EmojiDetails(Emoji.BabyAngel, new[] { 0x1F47C }, true), new EmojiDetails(Emoji.FatherChristmas, new[] { 0x1F385 }, true), new EmojiDetails(Emoji.MotherChristmas, new[] { 0x1F936 }, true),
            new EmojiDetails(Emoji.WomanWithBunnyEars, new[] { 0x1F46F }, true), new EmojiDetails(Emoji.ManInBusinessSuitLevitating, new[] { 0x1F574, 0xFE0F }, true), new EmojiDetails(Emoji.ManAndWomanHoldingHands, new[] { 0x1F46B }, true), new EmojiDetails(Emoji.TwoMenHoldingHands, new[] { 0x1F46C }, true),
            new EmojiDetails(Emoji.TwoWomenHoldingHands, new[] { 0x1F46D }, true), new EmojiDetails(Emoji.Family, new[] { 0x1F46A }, true), new EmojiDetails(Emoji.PersonFrowning, new[] { 0x1F64D }, true), new EmojiDetails(Emoji.PersonWithPoutingFace, new[] { 0x1F64E }, true),
            new EmojiDetails(Emoji.WhiteUpPointingIndex, new[] { 0x261D, 0xFE0F }, true), new EmojiDetails(Emoji.FaceWithNoGoodGesture, new[] { 0x1F645 }, true), new EmojiDetails(Emoji.VictoryHand, new[] { 0x270C, 0xFE0F }, true), new EmojiDetails(Emoji.FaceWithOKGesture, new[] { 0x1F646 }, true),
            new EmojiDetails(Emoji.RaisedHandWithFingersSplayed, new[] { 0x1F590, 0xFE0F }, true), new EmojiDetails(Emoji.InformationDeskPerson, new[] { 0x1F481 }, true), new EmojiDetails(Emoji.HappyPersonRaisingOneHand, new[] { 0x1F64B }, true),
            new EmojiDetails(Emoji.WritingHand, new[] { 0x270D, 0xFE0F }, true), new EmojiDetails(Emoji.PersonBowingDeeply, new[] { 0x1F647 }, true), new EmojiDetails(Emoji.Handshake, new[] { 0x1F91D }, true), new EmojiDetails(Emoji.FacePalm, new[] { 0x1F926 }, true),
            new EmojiDetails(Emoji.Shrug, new[] { 0x1F937 }, true), new EmojiDetails(Emoji.FaceMassage, new[] { 0x1F486 }, true), new EmojiDetails(Emoji.Haircut, new[] { 0x1F487 }, true), new EmojiDetails(Emoji.Pedestrian, new[] { 0x1F6B6 }, true), new EmojiDetails(Emoji.Runner, new[] { 0x1F3C3 }, true),
            new EmojiDetails(Emoji.Dancer, new[] { 0x1F483 }, true), new EmojiDetails(Emoji.ManDancing, new[] { 0x1F57A }, true), new EmojiDetails(Emoji.Bath, new[] { 0x1F6C0 }, true), new EmojiDetails(Emoji.SleepingAccommodation, new[] { 0x1F6CC }, true),
            new EmojiDetails(Emoji.SpeakingHeadInSilhouette, new[] { 0x1F5E3, 0xFE0F }), new EmojiDetails(Emoji.BustInSilhouette, new[] { 0x1F464 }), new EmojiDetails(Emoji.BustsInSilhouette, new[] { 0x1F465 }), new EmojiDetails(Emoji.Fencer, new[] { 0x1F93A }),
            new EmojiDetails(Emoji.HorseRacing, new[] { 0x1F3C7 }, true), new EmojiDetails(Emoji.Snowboarder, new[] { 0x1F3C2 }, true), new EmojiDetails(Emoji.Golfer, new[] { 0x1F3CC, 0xFE0F }, true), new EmojiDetails(Emoji.Surfer, new[] { 0x1F3C4 }, true),
            new EmojiDetails(Emoji.Rowboat, new[] { 0x1F6A3 }, true), new EmojiDetails(Emoji.Swimmer, new[] { 0x1F3CA }, true), new EmojiDetails(Emoji.PersonWithBall, new[] { 0x26F9, 0xFE0F }, true), new EmojiDetails(Emoji.WeightLifter, new[] { 0x1F3CB, 0xFE0F }, true),
            new EmojiDetails(Emoji.Bicyclist, new[] { 0x1F6B4 }, true), new EmojiDetails(Emoji.MountainBicyclist, new[] { 0x1F6B5 }, true), new EmojiDetails(Emoji.RacingCar, new[] { 0x1F3CE, 0xFE0F }), new EmojiDetails(Emoji.RacingMotorcycle, new[] { 0x1F3CD, 0xFE0F }),
            new EmojiDetails(Emoji.PersonDoingCartwheel, new[] { 0x1F938 }, true), new EmojiDetails(Emoji.Wrestlers, new[] { 0x1F93C }, true), new EmojiDetails(Emoji.WaterPolo, new[] { 0x1F93D }, true), new EmojiDetails(Emoji.Handball, new[] { 0x1F93E }, true),
            new EmojiDetails(Emoji.Juggling, new[] { 0x1F939 }, true), new EmojiDetails(Emoji.KissManMan, new[] { 0x1F468, 0x200D, 0x2764, 0xFE0F, 0x200D, 0x1F48B, 0x200D, 0x1F468 }), new EmojiDetails(Emoji.KissWomanWoman, new[] { 0x1F469, 0x200D, 0x2764, 0xFE0F, 0x200D, 0x1F48B, 0x200D, 0x1F469 }),
            new EmojiDetails(Emoji.CoupleWithHeartManMan, new[] { 0x1F468, 0x200D, 0x2764, 0xFE0F, 0x200D, 0x1F468 }), new EmojiDetails(Emoji.CoupleWithHeartWomanWoman, new[] { 0x1F469, 0x200D, 0x2764, 0xFE0F, 0x200D, 0x1F469 }),
            new EmojiDetails(Emoji.FamilyManWomanBoy, new[] { 0x1F468, 0x200D, 0x1F469, 0x200D, 0x1F466 }), new EmojiDetails(Emoji.FamilyManWomanGirl, new[] { 0x1F468, 0x200D, 0x1F469, 0x200D, 0x1F467 }),
            new EmojiDetails(Emoji.FamilyManWomanGirlBoy, new[] { 0x1F468, 0x200D, 0x1F469, 0x200D, 0x1F467, 0x200D, 0x1F466 }), new EmojiDetails(Emoji.FamilyManWomanBoyBoy, new[] { 0x1F468, 0x200D, 0x1F469, 0x200D, 0x1F466, 0x200D, 0x1F466 }),
            new EmojiDetails(Emoji.FamilyManWomanGirlGirl, new[] { 0x1F468, 0x200D, 0x1F469, 0x200D, 0x1F467, 0x200D, 0x1F467 }), new EmojiDetails(Emoji.FamilyManManBoy, new[] { 0x1F468, 0x200D, 0x1F468, 0x200D, 0x1F466 }),
            new EmojiDetails(Emoji.FamilyManManGirl, new[] { 0x1F468, 0x200D, 0x1F468, 0x200D, 0x1F467 }), new EmojiDetails(Emoji.FamilyManManGirlBoy, new[] { 0x1F468, 0x200D, 0x1F468, 0x200D, 0x1F467, 0x200D, 0x1F466 }),
            new EmojiDetails(Emoji.FamilyManManBoyBoy, new[] { 0x1F468, 0x200D, 0x1F468, 0x200D, 0x1F466, 0x200D, 0x1F466 }), new EmojiDetails(Emoji.FamilyManManGirlGirl, new[] { 0x1F468, 0x200D, 0x1F468, 0x200D, 0x1F467, 0x200D, 0x1F467 }),
            new EmojiDetails(Emoji.FamilyWomanWomanBoy, new[] { 0x1F469, 0x200D, 0x1F469, 0x200D, 0x1F466 }), new EmojiDetails(Emoji.FamilyWomanWomanGirl, new[] { 0x1F469, 0x200D, 0x1F469, 0x200D, 0x1F467 }),
            new EmojiDetails(Emoji.FamilyWomanWomanGirlBoy, new[] { 0x1F469, 0x200D, 0x1F469, 0x200D, 0x1F467, 0x200D, 0x1F466 }), new EmojiDetails(Emoji.FamilyWomanWomanBoyBoy, new[] { 0x1F469, 0x200D, 0x1F469, 0x200D, 0x1F466, 0x200D, 0x1F466 }),
            new EmojiDetails(Emoji.FamilyWomanWomanGirlGirl, new[] { 0x1F469, 0x200D, 0x1F469, 0x200D, 0x1F467, 0x200D, 0x1F467 }), new EmojiDetails(Emoji.FamilyManBoy, new[] { 0x1F468, 0x200D, 0x1F466 }), new EmojiDetails(Emoji.FamilyManBoyBoy, new[] { 0x1F468, 0x200D, 0x1F466, 0x200D, 0x1F466 }),
            new EmojiDetails(Emoji.FamilyManGirl, new[] { 0x1F468, 0x200D, 0x1F467 }), new EmojiDetails(Emoji.FamilyManGirlBoy, new[] { 0x1F468, 0x200D, 0x1F467, 0x200D, 0x1F466 }), new EmojiDetails(Emoji.FamilyManGirlGirl, new[] { 0x1F468, 0x200D, 0x1F467, 0x200D, 0x1F467 }),
            new EmojiDetails(Emoji.FamilyWomanBoy, new[] { 0x1F469, 0x200D, 0x1F466 }), new EmojiDetails(Emoji.FamilyWomanBoyBoy, new[] { 0x1F469, 0x200D, 0x1F466, 0x200D, 0x1F466 }), new EmojiDetails(Emoji.FamilyWomanGirl, new[] { 0x1F469, 0x200D, 0x1F467 }),
            new EmojiDetails(Emoji.FamilyWomanGirlBoy, new[] { 0x1F469, 0x200D, 0x1F467, 0x200D, 0x1F466 }), new EmojiDetails(Emoji.FamilyWomanGirlGirl, new[] { 0x1F469, 0x200D, 0x1F467, 0x200D, 0x1F467 }), new EmojiDetails(Emoji.Selfie, new[] { 0x1F933 }, true),
            new EmojiDetails(Emoji.FlexedBiceps, new[] { 0x1F4AA }, true), new EmojiDetails(Emoji.WhiteLeftPointingBackhandIndex, new[] { 0x1F448 }, true), new EmojiDetails(Emoji.WhiteRightPointingBackhandIndex, new[] { 0x1F449 }, true),
            new EmojiDetails(Emoji.WhiteUpPointingBackhandIndex, new[] { 0x1F446 }, true), new EmojiDetails(Emoji.ReversedHandWithMiddleFingerExtended, new[] { 0x1F595 }, true), new EmojiDetails(Emoji.WhiteDownPointingBackhandIndex, new[] { 0x1F447 }, true),
            new EmojiDetails(Emoji.HandWithIndexAndMiddleFingersCrossed, new[] { 0x1F91E }, true), new EmojiDetails(Emoji.RaisedHandWithPartBetweenMiddleAndRingFingers, new[] { 0x1F596 }, true), new EmojiDetails(Emoji.SignOfTheHorns, new[] { 0x1F918 }, true),
            new EmojiDetails(Emoji.CallMeHand, new[] { 0x1F919 }, true), new EmojiDetails(Emoji.RaisedHand, new[] { 0x270B }, true), new EmojiDetails(Emoji.OKHandSign, new[] { 0x1F44C }, true), new EmojiDetails(Emoji.ThumbsUpSign, new[] { 0x1F44D }, true),
            new EmojiDetails(Emoji.ThumbsDownSign, new[] { 0x1F44E }, true), new EmojiDetails(Emoji.RaisedFist, new[] { 0x270A }, true), new EmojiDetails(Emoji.FistedHandSign, new[] { 0x1F44A }, true), new EmojiDetails(Emoji.LeftFacingFist, new[] { 0x1F91B }, true),
            new EmojiDetails(Emoji.RightFacingFist, new[] { 0x1F91C }, true), new EmojiDetails(Emoji.RaisedBackOfHand, new[] { 0x1F91A }, true), new EmojiDetails(Emoji.WavingHandSign, new[] { 0x1F44B }, true), new EmojiDetails(Emoji.ClappingHandsSign, new[] { 0x1F44F }, true),
            new EmojiDetails(Emoji.OpenHandsSign, new[] { 0x1F450 }, true), new EmojiDetails(Emoji.PersonRaisingBothHandsInCelebration, new[] { 0x1F64C }, true), new EmojiDetails(Emoji.PersonWithFoldedHands, new[] { 0x1F64F }, true), new EmojiDetails(Emoji.NailPolish, new[] { 0x1F485 }, true),
            new EmojiDetails(Emoji.Ear, new[] { 0x1F442 }, true), new EmojiDetails(Emoji.Nose, new[] { 0x1F443 }, true), new EmojiDetails(Emoji.Footprints, new[] { 0x1F463 }), new EmojiDetails(Emoji.Eyes, new[] { 0x1F440 }), new EmojiDetails(Emoji.Eye, new[] { 0x1F441, 0xFE0F }),
            new EmojiDetails(Emoji.EyeInSpeechBubble, new[] { 0x1F441, 0x200D, 0x1F5E8 }), new EmojiDetails(Emoji.Tongue, new[] { 0x1F445 }), new EmojiDetails(Emoji.Mouth, new[] { 0x1F444 }), new EmojiDetails(Emoji.KissMark, new[] { 0x1F48B }), new EmojiDetails(Emoji.HeartWithArrow, new[] { 0x1F498 }),
            new EmojiDetails(Emoji.HeavyBlackHeart, new[] { 0x2764, 0xFE0F }), new EmojiDetails(Emoji.BeatingHeart, new[] { 0x1F493 }), new EmojiDetails(Emoji.BrokenHeart, new[] { 0x1F494 }), new EmojiDetails(Emoji.TwoHearts, new[] { 0x1F495 }), new EmojiDetails(Emoji.SparklingHeart, new[] { 0x1F496 }),
            new EmojiDetails(Emoji.GrowingHeart, new[] { 0x1F497 }), new EmojiDetails(Emoji.BlueHeart, new[] { 0x1F499 }), new EmojiDetails(Emoji.GreenHeart, new[] { 0x1F49A }), new EmojiDetails(Emoji.YellowHeart, new[] { 0x1F49B }), new EmojiDetails(Emoji.PurpleHeart, new[] { 0x1F49C }),
            new EmojiDetails(Emoji.BlackHeart, new[] { 0x1F5A4 }), new EmojiDetails(Emoji.HeartWithRibbon, new[] { 0x1F49D }), new EmojiDetails(Emoji.RevolvingHearts, new[] { 0x1F49E }), new EmojiDetails(Emoji.HeartDecoration, new[] { 0x1F49F }),
            new EmojiDetails(Emoji.HeavyHeartExclamationMarkOrnament, new[] { 0x2763, 0xFE0F }), new EmojiDetails(Emoji.LoveLetter, new[] { 0x1F48C }), new EmojiDetails(Emoji.SleepingSymbol, new[] { 0x1F4A4 }), new EmojiDetails(Emoji.AngerSymbol, new[] { 0x1F4A2 }),
            new EmojiDetails(Emoji.Bomb, new[] { 0x1F4A3 }), new EmojiDetails(Emoji.CollisionSymbol, new[] { 0x1F4A5 }), new EmojiDetails(Emoji.SplashingSweatSymbol, new[] { 0x1F4A6 }), new EmojiDetails(Emoji.DashSymbol, new[] { 0x1F4A8 }), new EmojiDetails(Emoji.DizzySymbol, new[] { 0x1F4AB }),
            new EmojiDetails(Emoji.SpeechBalloon, new[] { 0x1F4AC }), new EmojiDetails(Emoji.LeftSpeechBubble, new[] { 0x1F5E8, 0xFE0F }), new EmojiDetails(Emoji.RightAngerBubble, new[] { 0x1F5EF, 0xFE0F }), new EmojiDetails(Emoji.ThoughtBalloon, new[] { 0x1F4AD }),
            new EmojiDetails(Emoji.Hole, new[] { 0x1F573, 0xFE0F }), new EmojiDetails(Emoji.Eyeglasses, new[] { 0x1F453 }), new EmojiDetails(Emoji.DarkSunglasses, new[] { 0x1F576, 0xFE0F }), new EmojiDetails(Emoji.Necktie, new[] { 0x1F454 }), new EmojiDetails(Emoji.TShirt, new[] { 0x1F455 }),
            new EmojiDetails(Emoji.Jeans, new[] { 0x1F456 }), new EmojiDetails(Emoji.Dress, new[] { 0x1F457 }), new EmojiDetails(Emoji.Kimono, new[] { 0x1F458 }), new EmojiDetails(Emoji.Bikini, new[] { 0x1F459 }), new EmojiDetails(Emoji.WomansClothes, new[] { 0x1F45A }),
            new EmojiDetails(Emoji.Purse, new[] { 0x1F45B }), new EmojiDetails(Emoji.Handbag, new[] { 0x1F45C }), new EmojiDetails(Emoji.Pouch, new[] { 0x1F45D }), new EmojiDetails(Emoji.ShoppingBags, new[] { 0x1F6CD, 0xFE0F }), new EmojiDetails(Emoji.SchoolSatchel, new[] { 0x1F392 }),
            new EmojiDetails(Emoji.MansShoe, new[] { 0x1F45E }), new EmojiDetails(Emoji.AthleticShoe, new[] { 0x1F45F }), new EmojiDetails(Emoji.HighHeeledShoe, new[] { 0x1F460 }), new EmojiDetails(Emoji.WomansSandal, new[] { 0x1F461 }), new EmojiDetails(Emoji.WomansBoots, new[] { 0x1F462 }),
            new EmojiDetails(Emoji.Crown, new[] { 0x1F451 }), new EmojiDetails(Emoji.WomansHat, new[] { 0x1F452 }), new EmojiDetails(Emoji.TopHat, new[] { 0x1F3A9 }), new EmojiDetails(Emoji.GraduationCap, new[] { 0x1F393 }), new EmojiDetails(Emoji.PrayerBeads, new[] { 0x1F4FF }),
            new EmojiDetails(Emoji.Lipstick, new[] { 0x1F484 }), new EmojiDetails(Emoji.Ring, new[] { 0x1F48D }), new EmojiDetails(Emoji.GemStone, new[] { 0x1F48E }), new EmojiDetails(Emoji.MonkeyFace, new[] { 0x1F435 }), new EmojiDetails(Emoji.Monkey, new[] { 0x1F412 }),
            new EmojiDetails(Emoji.Gorilla, new[] { 0x1F98D }), new EmojiDetails(Emoji.DogFace, new[] { 0x1F436 }), new EmojiDetails(Emoji.Dog, new[] { 0x1F415 }), new EmojiDetails(Emoji.Poodle, new[] { 0x1F429 }), new EmojiDetails(Emoji.WolfFace, new[] { 0x1F43A }),
            new EmojiDetails(Emoji.FoxFace, new[] { 0x1F98A }), new EmojiDetails(Emoji.CatFace, new[] { 0x1F431 }), new EmojiDetails(Emoji.Cat, new[] { 0x1F408 }), new EmojiDetails(Emoji.LionFace, new[] { 0x1F981 }), new EmojiDetails(Emoji.TigerFace, new[] { 0x1F42F }),
            new EmojiDetails(Emoji.Tiger, new[] { 0x1F405 }), new EmojiDetails(Emoji.Leopard, new[] { 0x1F406 }), new EmojiDetails(Emoji.HorseFace, new[] { 0x1F434 }), new EmojiDetails(Emoji.Horse, new[] { 0x1F40E }), new EmojiDetails(Emoji.UnicornFace, new[] { 0x1F984 }),
            new EmojiDetails(Emoji.Deer, new[] { 0x1F98C }), new EmojiDetails(Emoji.CowFace, new[] { 0x1F42E }), new EmojiDetails(Emoji.Ox, new[] { 0x1F402 }), new EmojiDetails(Emoji.WaterBuffalo, new[] { 0x1F403 }), new EmojiDetails(Emoji.Cow, new[] { 0x1F404 }),
            new EmojiDetails(Emoji.PigFace, new[] { 0x1F437 }), new EmojiDetails(Emoji.Pig, new[] { 0x1F416 }), new EmojiDetails(Emoji.Boar, new[] { 0x1F417 }), new EmojiDetails(Emoji.PigNose, new[] { 0x1F43D }), new EmojiDetails(Emoji.Ram, new[] { 0x1F40F }), new EmojiDetails(Emoji.Sheep, new[] { 0x1F411 }),
            new EmojiDetails(Emoji.Goat, new[] { 0x1F410 }), new EmojiDetails(Emoji.DromedaryCamel, new[] { 0x1F42A }), new EmojiDetails(Emoji.BactrianCamel, new[] { 0x1F42B }), new EmojiDetails(Emoji.Elephant, new[] { 0x1F418 }), new EmojiDetails(Emoji.Rhinoceros, new[] { 0x1F98F }),
            new EmojiDetails(Emoji.MouseFace, new[] { 0x1F42D }), new EmojiDetails(Emoji.Mouse, new[] { 0x1F401 }), new EmojiDetails(Emoji.Rat, new[] { 0x1F400 }), new EmojiDetails(Emoji.HamsterFace, new[] { 0x1F439 }), new EmojiDetails(Emoji.RabbitFace, new[] { 0x1F430 }),
            new EmojiDetails(Emoji.Rabbit, new[] { 0x1F407 }), new EmojiDetails(Emoji.Chipmunk, new[] { 0x1F43F, 0xFE0F }), new EmojiDetails(Emoji.Bat, new[] { 0x1F987 }), new EmojiDetails(Emoji.BearFace, new[] { 0x1F43B }), new EmojiDetails(Emoji.Koala, new[] { 0x1F428 }),
            new EmojiDetails(Emoji.PandaFace, new[] { 0x1F43C }), new EmojiDetails(Emoji.PawPrints, new[] { 0x1F43E }), new EmojiDetails(Emoji.Turkey, new[] { 0x1F983 }), new EmojiDetails(Emoji.Chicken, new[] { 0x1F414 }), new EmojiDetails(Emoji.Rooster, new[] { 0x1F413 }),
            new EmojiDetails(Emoji.HatchingChick, new[] { 0x1F423 }), new EmojiDetails(Emoji.BabyChick, new[] { 0x1F424 }), new EmojiDetails(Emoji.FrontFacingBabyChick, new[] { 0x1F425 }), new EmojiDetails(Emoji.Bird, new[] { 0x1F426 }), new EmojiDetails(Emoji.Penguin, new[] { 0x1F427 }),
            new EmojiDetails(Emoji.DoveOfPeace, new[] { 0x1F54A, 0xFE0F }), new EmojiDetails(Emoji.Eagle, new[] { 0x1F985 }), new EmojiDetails(Emoji.Duck, new[] { 0x1F986 }), new EmojiDetails(Emoji.Owl, new[] { 0x1F989 }), new EmojiDetails(Emoji.FrogFace, new[] { 0x1F438 }),
            new EmojiDetails(Emoji.Crocodile, new[] { 0x1F40A }), new EmojiDetails(Emoji.Turtle, new[] { 0x1F422 }), new EmojiDetails(Emoji.Lizard, new[] { 0x1F98E }), new EmojiDetails(Emoji.Snake, new[] { 0x1F40D }), new EmojiDetails(Emoji.DragonFace, new[] { 0x1F432 }),
            new EmojiDetails(Emoji.Dragon, new[] { 0x1F409 }), new EmojiDetails(Emoji.SpoutingWhale, new[] { 0x1F433 }), new EmojiDetails(Emoji.Whale, new[] { 0x1F40B }), new EmojiDetails(Emoji.Dolphin, new[] { 0x1F42C }), new EmojiDetails(Emoji.Fish, new[] { 0x1F41F }),
            new EmojiDetails(Emoji.TropicalFish, new[] { 0x1F420 }), new EmojiDetails(Emoji.Blowfish, new[] { 0x1F421 }), new EmojiDetails(Emoji.Shark, new[] { 0x1F988 }), new EmojiDetails(Emoji.Octopus, new[] { 0x1F419 }), new EmojiDetails(Emoji.SpiralShell, new[] { 0x1F41A }),
            new EmojiDetails(Emoji.Crab, new[] { 0x1F980 }), new EmojiDetails(Emoji.Shrimp, new[] { 0x1F990 }), new EmojiDetails(Emoji.Squid, new[] { 0x1F991 }), new EmojiDetails(Emoji.Snail, new[] { 0x1F40C }), new EmojiDetails(Emoji.Butterfly, new[] { 0x1F98B }), new EmojiDetails(Emoji.Bug, new[] { 0x1F41B }),
            new EmojiDetails(Emoji.Ant, new[] { 0x1F41C }), new EmojiDetails(Emoji.Honeybee, new[] { 0x1F41D }), new EmojiDetails(Emoji.LadyBeetle, new[] { 0x1F41E }), new EmojiDetails(Emoji.Spider, new[] { 0x1F577, 0xFE0F }), new EmojiDetails(Emoji.SpiderWeb, new[] { 0x1F578, 0xFE0F }),
            new EmojiDetails(Emoji.Scorpion, new[] { 0x1F982 }), new EmojiDetails(Emoji.Bouquet, new[] { 0x1F490 }), new EmojiDetails(Emoji.CherryBlossom, new[] { 0x1F338 }), new EmojiDetails(Emoji.WhiteFlower, new[] { 0x1F4AE }), new EmojiDetails(Emoji.Rosette, new[] { 0x1F3F5, 0xFE0F }),
            new EmojiDetails(Emoji.Rose, new[] { 0x1F339 }), new EmojiDetails(Emoji.WiltedFlower, new[] { 0x1F940 }), new EmojiDetails(Emoji.Hibiscus, new[] { 0x1F33A }), new EmojiDetails(Emoji.Sunflower, new[] { 0x1F33B }), new EmojiDetails(Emoji.Blossom, new[] { 0x1F33C }),
            new EmojiDetails(Emoji.Tulip, new[] { 0x1F337 }), new EmojiDetails(Emoji.Seedling, new[] { 0x1F331 }), new EmojiDetails(Emoji.EvergreenTree, new[] { 0x1F332 }), new EmojiDetails(Emoji.DeciduousTree, new[] { 0x1F333 }), new EmojiDetails(Emoji.PalmTree, new[] { 0x1F334 }),
            new EmojiDetails(Emoji.Cactus, new[] { 0x1F335 }), new EmojiDetails(Emoji.EarOfRice, new[] { 0x1F33E }), new EmojiDetails(Emoji.Herb, new[] { 0x1F33F }), new EmojiDetails(Emoji.Shamrock, new[] { 0x2618, 0xFE0F }), new EmojiDetails(Emoji.FourLeafClover, new[] { 0x1F340 }),
            new EmojiDetails(Emoji.MapleLeaf, new[] { 0x1F341 }), new EmojiDetails(Emoji.FallenLeaf, new[] { 0x1F342 }), new EmojiDetails(Emoji.LeafFlutteringInWind, new[] { 0x1F343 }), new EmojiDetails(Emoji.Grapes, new[] { 0x1F347 }), new EmojiDetails(Emoji.Melon, new[] { 0x1F348 }),
            new EmojiDetails(Emoji.Watermelon, new[] { 0x1F349 }), new EmojiDetails(Emoji.Tangerine, new[] { 0x1F34A }), new EmojiDetails(Emoji.Lemon, new[] { 0x1F34B }), new EmojiDetails(Emoji.Banana, new[] { 0x1F34C }), new EmojiDetails(Emoji.Pineapple, new[] { 0x1F34D }),
            new EmojiDetails(Emoji.RedApple, new[] { 0x1F34E }), new EmojiDetails(Emoji.GreenApple, new[] { 0x1F34F }), new EmojiDetails(Emoji.Pear, new[] { 0x1F350 }), new EmojiDetails(Emoji.Peach, new[] { 0x1F351 }), new EmojiDetails(Emoji.Cherries, new[] { 0x1F352 }),
            new EmojiDetails(Emoji.Strawberry, new[] { 0x1F353 }), new EmojiDetails(Emoji.Kiwifruit, new[] { 0x1F95D }), new EmojiDetails(Emoji.Tomato, new[] { 0x1F345 }), new EmojiDetails(Emoji.Avocado, new[] { 0x1F951 }), new EmojiDetails(Emoji.Aubergine, new[] { 0x1F346 }),
            new EmojiDetails(Emoji.Potato, new[] { 0x1F954 }), new EmojiDetails(Emoji.Carrot, new[] { 0x1F955 }), new EmojiDetails(Emoji.EarOfMaize, new[] { 0x1F33D }), new EmojiDetails(Emoji.HotPepper, new[] { 0x1F336, 0xFE0F }), new EmojiDetails(Emoji.Cucumber, new[] { 0x1F952 }),
            new EmojiDetails(Emoji.Mushroom, new[] { 0x1F344 }), new EmojiDetails(Emoji.Peanuts, new[] { 0x1F95C }), new EmojiDetails(Emoji.Chestnut, new[] { 0x1F330 }), new EmojiDetails(Emoji.Bread, new[] { 0x1F35E }), new EmojiDetails(Emoji.Croissant, new[] { 0x1F950 }),
            new EmojiDetails(Emoji.BaguetteBread, new[] { 0x1F956 }), new EmojiDetails(Emoji.Pancakes, new[] { 0x1F95E }), new EmojiDetails(Emoji.CheeseWedge, new[] { 0x1F9C0 }), new EmojiDetails(Emoji.MeatOnBone, new[] { 0x1F356 }), new EmojiDetails(Emoji.PoultryLeg, new[] { 0x1F357 }),
            new EmojiDetails(Emoji.Bacon, new[] { 0x1F953 }), new EmojiDetails(Emoji.Hamburger, new[] { 0x1F354 }), new EmojiDetails(Emoji.FrenchFries, new[] { 0x1F35F }), new EmojiDetails(Emoji.SliceOfPizza, new[] { 0x1F355 }), new EmojiDetails(Emoji.HotDog, new[] { 0x1F32D }),
            new EmojiDetails(Emoji.Taco, new[] { 0x1F32E }), new EmojiDetails(Emoji.Burrito, new[] { 0x1F32F }), new EmojiDetails(Emoji.StuffedFlatbread, new[] { 0x1F959 }), new EmojiDetails(Emoji.Egg, new[] { 0x1F95A }), new EmojiDetails(Emoji.Cooking, new[] { 0x1F373 }),
            new EmojiDetails(Emoji.ShallowPanOfFood, new[] { 0x1F958 }), new EmojiDetails(Emoji.PotOfFood, new[] { 0x1F372 }), new EmojiDetails(Emoji.GreenSalad, new[] { 0x1F957 }), new EmojiDetails(Emoji.Popcorn, new[] { 0x1F37F }), new EmojiDetails(Emoji.BentoBox, new[] { 0x1F371 }),
            new EmojiDetails(Emoji.RiceCracker, new[] { 0x1F358 }), new EmojiDetails(Emoji.RiceBall, new[] { 0x1F359 }), new EmojiDetails(Emoji.CookedRice, new[] { 0x1F35A }), new EmojiDetails(Emoji.CurryAndRice, new[] { 0x1F35B }), new EmojiDetails(Emoji.SteamingBowl, new[] { 0x1F35C }),
            new EmojiDetails(Emoji.Spaghetti, new[] { 0x1F35D }), new EmojiDetails(Emoji.RoastedSweetPotato, new[] { 0x1F360 }), new EmojiDetails(Emoji.Oden, new[] { 0x1F362 }), new EmojiDetails(Emoji.Sushi, new[] { 0x1F363 }), new EmojiDetails(Emoji.FriedShrimp, new[] { 0x1F364 }),
            new EmojiDetails(Emoji.FishCakeWithSwirlDesign, new[] { 0x1F365 }), new EmojiDetails(Emoji.Dango, new[] { 0x1F361 }), new EmojiDetails(Emoji.SoftIceCream, new[] { 0x1F366 }), new EmojiDetails(Emoji.ShavedIce, new[] { 0x1F367 }), new EmojiDetails(Emoji.IceCream, new[] { 0x1F368 }),
            new EmojiDetails(Emoji.Doughnut, new[] { 0x1F369 }), new EmojiDetails(Emoji.Cookie, new[] { 0x1F36A }), new EmojiDetails(Emoji.BirthdayCake, new[] { 0x1F382 }), new EmojiDetails(Emoji.Shortcake, new[] { 0x1F370 }), new EmojiDetails(Emoji.ChocolateBar, new[] { 0x1F36B }),
            new EmojiDetails(Emoji.Candy, new[] { 0x1F36C }), new EmojiDetails(Emoji.Lollipop, new[] { 0x1F36D }), new EmojiDetails(Emoji.Custard, new[] { 0x1F36E }), new EmojiDetails(Emoji.HoneyPot, new[] { 0x1F36F }), new EmojiDetails(Emoji.BabyBottle, new[] { 0x1F37C }),
            new EmojiDetails(Emoji.GlassOfMilk, new[] { 0x1F95B }), new EmojiDetails(Emoji.HotBeverage, new[] { 0x2615 }), new EmojiDetails(Emoji.TeacupWithoutHandle, new[] { 0x1F375 }), new EmojiDetails(Emoji.SakeBottleAndCup, new[] { 0x1F376 }),
            new EmojiDetails(Emoji.BottleWithPoppingCork, new[] { 0x1F37E }), new EmojiDetails(Emoji.WineGlass, new[] { 0x1F377 }), new EmojiDetails(Emoji.CocktailGlass, new[] { 0x1F378 }), new EmojiDetails(Emoji.TropicalDrink, new[] { 0x1F379 }), new EmojiDetails(Emoji.BeerMug, new[] { 0x1F37A }),
            new EmojiDetails(Emoji.ClinkingBeerMugs, new[] { 0x1F37B }), new EmojiDetails(Emoji.ClinkingGlasses, new[] { 0x1F942 }), new EmojiDetails(Emoji.TumblerGlass, new[] { 0x1F943 }), new EmojiDetails(Emoji.ForkAndKnifeWithPlate, new[] { 0x1F37D, 0xFE0F }),
            new EmojiDetails(Emoji.ForkAndKnife, new[] { 0x1F374 }), new EmojiDetails(Emoji.Spoon, new[] { 0x1F944 }), new EmojiDetails(Emoji.Hocho, new[] { 0x1F52A }), new EmojiDetails(Emoji.Amphora, new[] { 0x1F3FA }), new EmojiDetails(Emoji.EarthGlobeEuropeAfrica, new[] { 0x1F30D }),
            new EmojiDetails(Emoji.EarthGlobeAmericas, new[] { 0x1F30E }), new EmojiDetails(Emoji.EarthGlobeAsiaAustralia, new[] { 0x1F30F }), new EmojiDetails(Emoji.GlobeWithMeridians, new[] { 0x1F310 }), new EmojiDetails(Emoji.WorldMap, new[] { 0x1F5FA, 0xFE0F }),
            new EmojiDetails(Emoji.SilhouetteOfJapan, new[] { 0x1F5FE }), new EmojiDetails(Emoji.SnowCappedMountain, new[] { 0x1F3D4, 0xFE0F }), new EmojiDetails(Emoji.Mountain, new[] { 0x26F0, 0xFE0F }), new EmojiDetails(Emoji.Volcano, new[] { 0x1F30B }), new EmojiDetails(Emoji.MountFuji, new[] { 0x1F5FB }),
            new EmojiDetails(Emoji.Camping, new[] { 0x1F3D5, 0xFE0F }), new EmojiDetails(Emoji.BeachWithUmbrella, new[] { 0x1F3D6, 0xFE0F }), new EmojiDetails(Emoji.Desert, new[] { 0x1F3DC, 0xFE0F }), new EmojiDetails(Emoji.DesertIsland, new[] { 0x1F3DD, 0xFE0F }),
            new EmojiDetails(Emoji.NationalPark, new[] { 0x1F3DE, 0xFE0F }), new EmojiDetails(Emoji.Stadium, new[] { 0x1F3DF, 0xFE0F }), new EmojiDetails(Emoji.ClassicalBuilding, new[] { 0x1F3DB, 0xFE0F }), new EmojiDetails(Emoji.BuildingConstruction, new[] { 0x1F3D7, 0xFE0F }),
            new EmojiDetails(Emoji.HouseBuildings, new[] { 0x1F3D8, 0xFE0F }), new EmojiDetails(Emoji.Cityscape, new[] { 0x1F3D9, 0xFE0F }), new EmojiDetails(Emoji.DerelictHouseBuilding, new[] { 0x1F3DA, 0xFE0F }), new EmojiDetails(Emoji.HouseBuilding, new[] { 0x1F3E0 }),
            new EmojiDetails(Emoji.HouseWithGarden, new[] { 0x1F3E1 }), new EmojiDetails(Emoji.OfficeBuilding, new[] { 0x1F3E2 }), new EmojiDetails(Emoji.JapanesePostOffice, new[] { 0x1F3E3 }), new EmojiDetails(Emoji.EuropeanPostOffice, new[] { 0x1F3E4 }), new EmojiDetails(Emoji.Hospital, new[] { 0x1F3E5 }),
            new EmojiDetails(Emoji.Bank, new[] { 0x1F3E6 }), new EmojiDetails(Emoji.Hotel, new[] { 0x1F3E8 }), new EmojiDetails(Emoji.LoveHotel, new[] { 0x1F3E9 }), new EmojiDetails(Emoji.ConvenienceStore, new[] { 0x1F3EA }), new EmojiDetails(Emoji.School, new[] { 0x1F3EB }),
            new EmojiDetails(Emoji.DepartmentStore, new[] { 0x1F3EC }), new EmojiDetails(Emoji.Factory, new[] { 0x1F3ED }), new EmojiDetails(Emoji.JapaneseCastle, new[] { 0x1F3EF }), new EmojiDetails(Emoji.EuropeanCastle, new[] { 0x1F3F0 }), new EmojiDetails(Emoji.Wedding, new[] { 0x1F492 }),
            new EmojiDetails(Emoji.TokyoTower, new[] { 0x1F5FC }), new EmojiDetails(Emoji.StatueOfLiberty, new[] { 0x1F5FD }), new EmojiDetails(Emoji.Church, new[] { 0x26EA }), new EmojiDetails(Emoji.Mosque, new[] { 0x1F54C }), new EmojiDetails(Emoji.Synagogue, new[] { 0x1F54D }),
            new EmojiDetails(Emoji.ShintoShrine, new[] { 0x26E9, 0xFE0F }), new EmojiDetails(Emoji.Kaaba, new[] { 0x1F54B }), new EmojiDetails(Emoji.Fountain, new[] { 0x26F2 }), new EmojiDetails(Emoji.Tent, new[] { 0x26FA }), new EmojiDetails(Emoji.Foggy, new[] { 0x1F301 }),
            new EmojiDetails(Emoji.NightWithStars, new[] { 0x1F303 }), new EmojiDetails(Emoji.SunriseOverMountains, new[] { 0x1F304 }), new EmojiDetails(Emoji.Sunrise, new[] { 0x1F305 }), new EmojiDetails(Emoji.CityscapeAtDusk, new[] { 0x1F306 }), new EmojiDetails(Emoji.SunsetOverBuildings, new[] { 0x1F307 }),
            new EmojiDetails(Emoji.BridgeAtNight, new[] { 0x1F309 }), new EmojiDetails(Emoji.HotSprings, new[] { 0x2668, 0xFE0F }), new EmojiDetails(Emoji.MilkyWay, new[] { 0x1F30C }), new EmojiDetails(Emoji.CarouselHorse, new[] { 0x1F3A0 }), new EmojiDetails(Emoji.FerrisWheel, new[] { 0x1F3A1 }),
            new EmojiDetails(Emoji.RollerCoaster, new[] { 0x1F3A2 }), new EmojiDetails(Emoji.BarberPole, new[] { 0x1F488 }), new EmojiDetails(Emoji.CircusTent, new[] { 0x1F3AA }), new EmojiDetails(Emoji.PerformingArts, new[] { 0x1F3AD }), new EmojiDetails(Emoji.FrameWithPicture, new[] { 0x1F5BC, 0xFE0F }),
            new EmojiDetails(Emoji.ArtistPalette, new[] { 0x1F3A8 }), new EmojiDetails(Emoji.SlotMachine, new[] { 0x1F3B0 }), new EmojiDetails(Emoji.SteamLocomotive, new[] { 0x1F682 }), new EmojiDetails(Emoji.RailwayCar, new[] { 0x1F683 }), new EmojiDetails(Emoji.HighSpeedTrain, new[] { 0x1F684 }),
            new EmojiDetails(Emoji.HighSpeedTrainWithBulletNose, new[] { 0x1F685 }), new EmojiDetails(Emoji.Train, new[] { 0x1F686 }), new EmojiDetails(Emoji.Metro, new[] { 0x1F687 }), new EmojiDetails(Emoji.LightRail, new[] { 0x1F688 }), new EmojiDetails(Emoji.Station, new[] { 0x1F689 }),
            new EmojiDetails(Emoji.Tram, new[] { 0x1F68A }), new EmojiDetails(Emoji.Monorail, new[] { 0x1F69D }), new EmojiDetails(Emoji.MountainRailway, new[] { 0x1F69E }), new EmojiDetails(Emoji.TramCar, new[] { 0x1F68B }), new EmojiDetails(Emoji.Bus, new[] { 0x1F68C }),
            new EmojiDetails(Emoji.OncomingBus, new[] { 0x1F68D }), new EmojiDetails(Emoji.Trolleybus, new[] { 0x1F68E }), new EmojiDetails(Emoji.Minibus, new[] { 0x1F690 }), new EmojiDetails(Emoji.Ambulance, new[] { 0x1F691 }), new EmojiDetails(Emoji.FireEngine, new[] { 0x1F692 }),
            new EmojiDetails(Emoji.PoliceCar, new[] { 0x1F693 }), new EmojiDetails(Emoji.OncomingPoliceCar, new[] { 0x1F694 }), new EmojiDetails(Emoji.Taxi, new[] { 0x1F695 }), new EmojiDetails(Emoji.OncomingTaxi, new[] { 0x1F696 }), new EmojiDetails(Emoji.Automobile, new[] { 0x1F697 }),
            new EmojiDetails(Emoji.OncomingAutomobile, new[] { 0x1F698 }), new EmojiDetails(Emoji.RecreationalVehicle, new[] { 0x1F699 }), new EmojiDetails(Emoji.DeliveryTruck, new[] { 0x1F69A }), new EmojiDetails(Emoji.ArticulatedLorry, new[] { 0x1F69B }), new EmojiDetails(Emoji.Tractor, new[] { 0x1F69C }),
            new EmojiDetails(Emoji.Bicycle, new[] { 0x1F6B2 }), new EmojiDetails(Emoji.Scooter, new[] { 0x1F6F4 }), new EmojiDetails(Emoji.MotorScooter, new[] { 0x1F6F5 }), new EmojiDetails(Emoji.BusStop, new[] { 0x1F68F }), new EmojiDetails(Emoji.Motorway, new[] { 0x1F6E3, 0xFE0F }),
            new EmojiDetails(Emoji.RailwayTrack, new[] { 0x1F6E4, 0xFE0F }), new EmojiDetails(Emoji.FuelPump, new[] { 0x26FD }), new EmojiDetails(Emoji.PoliceCarsRevolvingLight, new[] { 0x1F6A8 }), new EmojiDetails(Emoji.HorizontalTrafficLight, new[] { 0x1F6A5 }),
            new EmojiDetails(Emoji.VerticalTrafficLight, new[] { 0x1F6A6 }), new EmojiDetails(Emoji.ConstructionSign, new[] { 0x1F6A7 }), new EmojiDetails(Emoji.OctagonalSign, new[] { 0x1F6D1 }), new EmojiDetails(Emoji.Anchor, new[] { 0x2693 }), new EmojiDetails(Emoji.Sailboat, new[] { 0x26F5 }),
            new EmojiDetails(Emoji.Canoe, new[] { 0x1F6F6 }), new EmojiDetails(Emoji.Speedboat, new[] { 0x1F6A4 }), new EmojiDetails(Emoji.PassengerShip, new[] { 0x1F6F3, 0xFE0F }), new EmojiDetails(Emoji.Ferry, new[] { 0x26F4, 0xFE0F }), new EmojiDetails(Emoji.MotorBoat, new[] { 0x1F6E5, 0xFE0F }),
            new EmojiDetails(Emoji.Ship, new[] { 0x1F6A2 }), new EmojiDetails(Emoji.Airplane, new[] { 0x2708, 0xFE0F }), new EmojiDetails(Emoji.SmallAirplane, new[] { 0x1F6E9, 0xFE0F }), new EmojiDetails(Emoji.AirplaneDeparture, new[] { 0x1F6EB }), new EmojiDetails(Emoji.AirplaneArriving, new[] { 0x1F6EC }),
            new EmojiDetails(Emoji.Seat, new[] { 0x1F4BA }), new EmojiDetails(Emoji.Helicopter, new[] { 0x1F681 }), new EmojiDetails(Emoji.SuspensionRailway, new[] { 0x1F69F }), new EmojiDetails(Emoji.MountainCableway, new[] { 0x1F6A0 }), new EmojiDetails(Emoji.AerialTramway, new[] { 0x1F6A1 }),
            new EmojiDetails(Emoji.Satellite, new[] { 0x1F6F0, 0xFE0F }), new EmojiDetails(Emoji.Rocket, new[] { 0x1F680 }), new EmojiDetails(Emoji.BellhopBell, new[] { 0x1F6CE, 0xFE0F }), new EmojiDetails(Emoji.Door, new[] { 0x1F6AA }), new EmojiDetails(Emoji.Bed, new[] { 0x1F6CF, 0xFE0F }),
            new EmojiDetails(Emoji.CouchAndLamp, new[] { 0x1F6CB, 0xFE0F }), new EmojiDetails(Emoji.Toilet, new[] { 0x1F6BD }), new EmojiDetails(Emoji.Shower, new[] { 0x1F6BF }), new EmojiDetails(Emoji.Bathtub, new[] { 0x1F6C1 }), new EmojiDetails(Emoji.Hourglass, new[] { 0x231B }),
            new EmojiDetails(Emoji.HourglassWithFlowingSand, new[] { 0x23F3 }), new EmojiDetails(Emoji.Watch, new[] { 0x231A }), new EmojiDetails(Emoji.AlarmClock, new[] { 0x23F0 }), new EmojiDetails(Emoji.Stopwatch, new[] { 0x23F1, 0xFE0F }), new EmojiDetails(Emoji.TimerClock, new[] { 0x23F2, 0xFE0F }),
            new EmojiDetails(Emoji.MantelpieceClock, new[] { 0x1F570, 0xFE0F }), new EmojiDetails(Emoji.ClockFaceTwelveOClock, new[] { 0x1F55B }), new EmojiDetails(Emoji.ClockFaceTwelveThirty, new[] { 0x1F567 }), new EmojiDetails(Emoji.ClockFaceOneOClock, new[] { 0x1F550 }),
            new EmojiDetails(Emoji.ClockFaceOneThirty, new[] { 0x1F55C }), new EmojiDetails(Emoji.ClockFaceTwoOClock, new[] { 0x1F551 }), new EmojiDetails(Emoji.ClockFaceTwoThirty, new[] { 0x1F55D }), new EmojiDetails(Emoji.ClockFaceThreeOClock, new[] { 0x1F552 }),
            new EmojiDetails(Emoji.ClockFaceThreeThirty, new[] { 0x1F55E }), new EmojiDetails(Emoji.ClockFaceFourOClock, new[] { 0x1F553 }), new EmojiDetails(Emoji.ClockFaceFourThirty, new[] { 0x1F55F }), new EmojiDetails(Emoji.ClockFaceFiveOClock, new[] { 0x1F554 }),
            new EmojiDetails(Emoji.ClockFaceFiveThirty, new[] { 0x1F560 }), new EmojiDetails(Emoji.ClockFaceSixOClock, new[] { 0x1F555 }), new EmojiDetails(Emoji.ClockFaceSixThirty, new[] { 0x1F561 }), new EmojiDetails(Emoji.ClockFaceSevenOClock, new[] { 0x1F556 }),
            new EmojiDetails(Emoji.ClockFaceSevenThirty, new[] { 0x1F562 }), new EmojiDetails(Emoji.ClockFaceEightOClock, new[] { 0x1F557 }), new EmojiDetails(Emoji.ClockFaceEightThirty, new[] { 0x1F563 }), new EmojiDetails(Emoji.ClockFaceNineOClock, new[] { 0x1F558 }),
            new EmojiDetails(Emoji.ClockFaceNineThirty, new[] { 0x1F564 }), new EmojiDetails(Emoji.ClockFaceTenOClock, new[] { 0x1F559 }), new EmojiDetails(Emoji.ClockFaceTenThirty, new[] { 0x1F565 }), new EmojiDetails(Emoji.ClockFaceElevenOClock, new[] { 0x1F55A }),
            new EmojiDetails(Emoji.ClockFaceElevenThirty, new[] { 0x1F566 }), new EmojiDetails(Emoji.NewMoonSymbol, new[] { 0x1F311 }), new EmojiDetails(Emoji.WaxingCrescentMoonSymbol, new[] { 0x1F312 }), new EmojiDetails(Emoji.FirstQuarterMoonSymbol, new[] { 0x1F313 }),
            new EmojiDetails(Emoji.WaxingGibbousMoonSymbol, new[] { 0x1F314 }), new EmojiDetails(Emoji.FullMoonSymbol, new[] { 0x1F315 }), new EmojiDetails(Emoji.WaningGibbousMoonSymbol, new[] { 0x1F316 }), new EmojiDetails(Emoji.LastQuarterMoonSymbol, new[] { 0x1F317 }),
            new EmojiDetails(Emoji.WaningCrescentMoonSymbol, new[] { 0x1F318 }), new EmojiDetails(Emoji.CrescentMoon, new[] { 0x1F319 }), new EmojiDetails(Emoji.NewMoonWithFace, new[] { 0x1F31A }), new EmojiDetails(Emoji.FirstQuarterMoonWithFace, new[] { 0x1F31B }),
            new EmojiDetails(Emoji.LastQuarterMoonWithFace, new[] { 0x1F31C }), new EmojiDetails(Emoji.Thermometer, new[] { 0x1F321, 0xFE0F }), new EmojiDetails(Emoji.BlackSunWithRays, new[] { 0x2600, 0xFE0F }), new EmojiDetails(Emoji.FullMoonWithFace, new[] { 0x1F31D }),
            new EmojiDetails(Emoji.SunWithFace, new[] { 0x1F31E }), new EmojiDetails(Emoji.WhiteMediumStar, new[] { 0x2B50 }), new EmojiDetails(Emoji.GlowingStar, new[] { 0x1F31F }), new EmojiDetails(Emoji.ShootingStar, new[] { 0x1F320 }), new EmojiDetails(Emoji.Cloud, new[] { 0x2601, 0xFE0F }),
            new EmojiDetails(Emoji.SunBehindCloud, new[] { 0x26C5 }), new EmojiDetails(Emoji.ThunderCloudAndRain, new[] { 0x26C8, 0xFE0F }), new EmojiDetails(Emoji.WhiteSunWithSmallCloud, new[] { 0x1F324, 0xFE0F }), new EmojiDetails(Emoji.WhiteSunBehindCloud, new[] { 0x1F325, 0xFE0F }),
            new EmojiDetails(Emoji.WhiteSunBehindCloudWithRain, new[] { 0x1F326, 0xFE0F }), new EmojiDetails(Emoji.CloudWithRain, new[] { 0x1F327, 0xFE0F }), new EmojiDetails(Emoji.CloudWithSnow, new[] { 0x1F328, 0xFE0F }), new EmojiDetails(Emoji.CloudWithLightning, new[] { 0x1F329, 0xFE0F }),
            new EmojiDetails(Emoji.CloudWithTornado, new[] { 0x1F32A, 0xFE0F }), new EmojiDetails(Emoji.Fog, new[] { 0x1F32B, 0xFE0F }), new EmojiDetails(Emoji.WindBlowingFace, new[] { 0x1F32C, 0xFE0F }), new EmojiDetails(Emoji.Cyclone, new[] { 0x1F300 }), new EmojiDetails(Emoji.Rainbow, new[] { 0x1F308 }),
            new EmojiDetails(Emoji.ClosedUmbrella, new[] { 0x1F302 }), new EmojiDetails(Emoji.Umbrella, new[] { 0x2602, 0xFE0F }), new EmojiDetails(Emoji.UmbrellaWithRainDrops, new[] { 0x2614 }), new EmojiDetails(Emoji.UmbrellaOnGround, new[] { 0x26F1, 0xFE0F }),
            new EmojiDetails(Emoji.HighVoltageSign, new[] { 0x26A1 }), new EmojiDetails(Emoji.Snowflake, new[] { 0x2744, 0xFE0F }), new EmojiDetails(Emoji.Snowman, new[] { 0x2603, 0xFE0F }), new EmojiDetails(Emoji.SnowmanWithoutSnow, new[] { 0x26C4 }), new EmojiDetails(Emoji.Comet, new[] { 0x2604, 0xFE0F }),
            new EmojiDetails(Emoji.Fire, new[] { 0x1F525 }), new EmojiDetails(Emoji.Droplet, new[] { 0x1F4A7 }), new EmojiDetails(Emoji.WaterWave, new[] { 0x1F30A }), new EmojiDetails(Emoji.JackOLantern, new[] { 0x1F383 }), new EmojiDetails(Emoji.ChristmasTree, new[] { 0x1F384 }),
            new EmojiDetails(Emoji.Fireworks, new[] { 0x1F386 }), new EmojiDetails(Emoji.FireworkSparkler, new[] { 0x1F387 }), new EmojiDetails(Emoji.Sparkles, new[] { 0x2728 }), new EmojiDetails(Emoji.Balloon, new[] { 0x1F388 }), new EmojiDetails(Emoji.PartyPopper, new[] { 0x1F389 }),
            new EmojiDetails(Emoji.ConfettiBall, new[] { 0x1F38A }), new EmojiDetails(Emoji.TanabataTree, new[] { 0x1F38B }), new EmojiDetails(Emoji.PineDecoration, new[] { 0x1F38D }), new EmojiDetails(Emoji.JapaneseDolls, new[] { 0x1F38E }), new EmojiDetails(Emoji.CarpStreamer, new[] { 0x1F38F }),
            new EmojiDetails(Emoji.WindChime, new[] { 0x1F390 }), new EmojiDetails(Emoji.MoonViewingCeremony, new[] { 0x1F391 }), new EmojiDetails(Emoji.Ribbon, new[] { 0x1F380 }), new EmojiDetails(Emoji.WrappedPresent, new[] { 0x1F381 }), new EmojiDetails(Emoji.ReminderRibbon, new[] { 0x1F397, 0xFE0F }),
            new EmojiDetails(Emoji.AdmissionTickets, new[] { 0x1F39F, 0xFE0F }), new EmojiDetails(Emoji.Ticket, new[] { 0x1F3AB }), new EmojiDetails(Emoji.MilitaryMedal, new[] { 0x1F396, 0xFE0F }), new EmojiDetails(Emoji.Trophy, new[] { 0x1F3C6 }), new EmojiDetails(Emoji.SportsMedal, new[] { 0x1F3C5 }),
            new EmojiDetails(Emoji.FirstPlaceMedal, new[] { 0x1F947 }), new EmojiDetails(Emoji.SecondPlaceMedal, new[] { 0x1F948 }), new EmojiDetails(Emoji.ThirdPlaceMedal, new[] { 0x1F949 }), new EmojiDetails(Emoji.SoccerBall, new[] { 0x26BD }), new EmojiDetails(Emoji.Baseball, new[] { 0x26BE }),
            new EmojiDetails(Emoji.BasketballAndHoop, new[] { 0x1F3C0 }), new EmojiDetails(Emoji.Volleyball, new[] { 0x1F3D0 }), new EmojiDetails(Emoji.AmericanFootball, new[] { 0x1F3C8 }), new EmojiDetails(Emoji.RugbyFootball, new[] { 0x1F3C9 }),
            new EmojiDetails(Emoji.TennisRacquetAndBall, new[] { 0x1F3BE }), new EmojiDetails(Emoji.Billiards, new[] { 0x1F3B1 }), new EmojiDetails(Emoji.Bowling, new[] { 0x1F3B3 }), new EmojiDetails(Emoji.CricketBatAndBall, new[] { 0x1F3CF }),
            new EmojiDetails(Emoji.FieldHockeyStickAndBall, new[] { 0x1F3D1 }), new EmojiDetails(Emoji.IceHockeyStickAndPuck, new[] { 0x1F3D2 }), new EmojiDetails(Emoji.TableTennisPaddleAndBall, new[] { 0x1F3D3 }), new EmojiDetails(Emoji.BadmintonRacquetAndShuttlecock, new[] { 0x1F3F8 }),
            new EmojiDetails(Emoji.BoxingGlove, new[] { 0x1F94A }), new EmojiDetails(Emoji.MartialArtsUniform, new[] { 0x1F94B }), new EmojiDetails(Emoji.GoalNet, new[] { 0x1F945 }), new EmojiDetails(Emoji.DirectHit, new[] { 0x1F3AF }), new EmojiDetails(Emoji.FlagInHole, new[] { 0x26F3 }),
            new EmojiDetails(Emoji.IceSkate, new[] { 0x26F8, 0xFE0F }), new EmojiDetails(Emoji.FishingPoleAndFish, new[] { 0x1F3A3 }), new EmojiDetails(Emoji.RunningShirtWithSash, new[] { 0x1F3BD }), new EmojiDetails(Emoji.SkiAndSkiBoot, new[] { 0x1F3BF }), new EmojiDetails(Emoji.VideoGame, new[] { 0x1F3AE }),
            new EmojiDetails(Emoji.Joystick, new[] { 0x1F579, 0xFE0F }), new EmojiDetails(Emoji.GameDie, new[] { 0x1F3B2 }), new EmojiDetails(Emoji.BlackSpadeSuit, new[] { 0x2660, 0xFE0F }), new EmojiDetails(Emoji.BlackHeartSuit, new[] { 0x2665, 0xFE0F }),
            new EmojiDetails(Emoji.BlackDiamondSuit, new[] { 0x2666, 0xFE0F }), new EmojiDetails(Emoji.BlackClubSuit, new[] { 0x2663, 0xFE0F }), new EmojiDetails(Emoji.PlayingCardBlackJoker, new[] { 0x1F0CF }), new EmojiDetails(Emoji.MahjongTileRedDragon, new[] { 0x1F004 }),
            new EmojiDetails(Emoji.FlowerPlayingCards, new[] { 0x1F3B4 }), new EmojiDetails(Emoji.SpeakerWithCancellationStroke, new[] { 0x1F507 }), new EmojiDetails(Emoji.Speaker, new[] { 0x1F508 }), new EmojiDetails(Emoji.SpeakerWithOneSoundWave, new[] { 0x1F509 }),
            new EmojiDetails(Emoji.SpeakerWithThreeSoundWaves, new[] { 0x1F50A }), new EmojiDetails(Emoji.PublicAddressLoudspeaker, new[] { 0x1F4E2 }), new EmojiDetails(Emoji.CheeringMegaphone, new[] { 0x1F4E3 }), new EmojiDetails(Emoji.PostalHorn, new[] { 0x1F4EF }),
            new EmojiDetails(Emoji.Bell, new[] { 0x1F514 }), new EmojiDetails(Emoji.BellWithCancellationStroke, new[] { 0x1F515 }), new EmojiDetails(Emoji.MusicalScore, new[] { 0x1F3BC }), new EmojiDetails(Emoji.MusicalNote, new[] { 0x1F3B5 }), new EmojiDetails(Emoji.MultipleMusicalNotes, new[] { 0x1F3B6 }),
            new EmojiDetails(Emoji.StudioMicrophone, new[] { 0x1F399, 0xFE0F }), new EmojiDetails(Emoji.LevelSlider, new[] { 0x1F39A, 0xFE0F }), new EmojiDetails(Emoji.ControlKnobs, new[] { 0x1F39B, 0xFE0F }), new EmojiDetails(Emoji.Microphone, new[] { 0x1F3A4 }),
            new EmojiDetails(Emoji.Headphone, new[] { 0x1F3A7 }), new EmojiDetails(Emoji.Radio, new[] { 0x1F4FB }), new EmojiDetails(Emoji.Saxophone, new[] { 0x1F3B7 }), new EmojiDetails(Emoji.Guitar, new[] { 0x1F3B8 }), new EmojiDetails(Emoji.MusicalKeyboard, new[] { 0x1F3B9 }),
            new EmojiDetails(Emoji.Trumpet, new[] { 0x1F3BA }), new EmojiDetails(Emoji.Violin, new[] { 0x1F3BB }), new EmojiDetails(Emoji.DrumWithDrumsticks, new[] { 0x1F941 }), new EmojiDetails(Emoji.MobilePhone, new[] { 0x1F4F1 }),
            new EmojiDetails(Emoji.MobilePhoneWithRightwardsArrowAtLeft, new[] { 0x1F4F2 }), new EmojiDetails(Emoji.BlackTelephone, new[] { 0x260E, 0xFE0F }), new EmojiDetails(Emoji.TelephoneReceiver, new[] { 0x1F4DE }), new EmojiDetails(Emoji.Pager, new[] { 0x1F4DF }),
            new EmojiDetails(Emoji.FaxMachine, new[] { 0x1F4E0 }), new EmojiDetails(Emoji.Battery, new[] { 0x1F50B }), new EmojiDetails(Emoji.ElectricPlug, new[] { 0x1F50C }), new EmojiDetails(Emoji.PersonalComputer, new[] { 0x1F4BB }), new EmojiDetails(Emoji.DesktopComputer, new[] { 0x1F5A5, 0xFE0F }),
            new EmojiDetails(Emoji.Printer, new[] { 0x1F5A8, 0xFE0F }), new EmojiDetails(Emoji.Keyboard, new[] { 0x2328, 0xFE0F }), new EmojiDetails(Emoji.ThreeButtonMouse, new[] { 0x1F5B1, 0xFE0F }), new EmojiDetails(Emoji.Trackball, new[] { 0x1F5B2, 0xFE0F }),
            new EmojiDetails(Emoji.Minidisc, new[] { 0x1F4BD }), new EmojiDetails(Emoji.FloppyDisk, new[] { 0x1F4BE }), new EmojiDetails(Emoji.OpticalDisc, new[] { 0x1F4BF }), new EmojiDetails(Emoji.DVD, new[] { 0x1F4C0 }), new EmojiDetails(Emoji.MovieCamera, new[] { 0x1F3A5 }),
            new EmojiDetails(Emoji.FilmFrames, new[] { 0x1F39E, 0xFE0F }), new EmojiDetails(Emoji.FilmProjector, new[] { 0x1F4FD, 0xFE0F }), new EmojiDetails(Emoji.ClapperBoard, new[] { 0x1F3AC }), new EmojiDetails(Emoji.Television, new[] { 0x1F4FA }), new EmojiDetails(Emoji.Camera, new[] { 0x1F4F7 }),
            new EmojiDetails(Emoji.CameraWithFlash, new[] { 0x1F4F8 }), new EmojiDetails(Emoji.VideoCamera, new[] { 0x1F4F9 }), new EmojiDetails(Emoji.Videocassette, new[] { 0x1F4FC }), new EmojiDetails(Emoji.LeftPointingMagnifyingGlass, new[] { 0x1F50D }),
            new EmojiDetails(Emoji.RightPointingMagnifyingGlass, new[] { 0x1F50E }), new EmojiDetails(Emoji.Microscope, new[] { 0x1F52C }), new EmojiDetails(Emoji.Telescope, new[] { 0x1F52D }), new EmojiDetails(Emoji.SatelliteAntenna, new[] { 0x1F4E1 }),
            new EmojiDetails(Emoji.Candle, new[] { 0x1F56F, 0xFE0F }), new EmojiDetails(Emoji.ElectricLightBulb, new[] { 0x1F4A1 }), new EmojiDetails(Emoji.ElectricTorch, new[] { 0x1F526 }), new EmojiDetails(Emoji.IzakayaLantern, new[] { 0x1F3EE }),
            new EmojiDetails(Emoji.NotebookWithDecorativeCover, new[] { 0x1F4D4 }), new EmojiDetails(Emoji.ClosedBook, new[] { 0x1F4D5 }), new EmojiDetails(Emoji.OpenBook, new[] { 0x1F4D6 }), new EmojiDetails(Emoji.GreenBook, new[] { 0x1F4D7 }), new EmojiDetails(Emoji.BlueBook, new[] { 0x1F4D8 }),
            new EmojiDetails(Emoji.OrangeBook, new[] { 0x1F4D9 }), new EmojiDetails(Emoji.Books, new[] { 0x1F4DA }), new EmojiDetails(Emoji.Notebook, new[] { 0x1F4D3 }), new EmojiDetails(Emoji.Ledger, new[] { 0x1F4D2 }), new EmojiDetails(Emoji.PageWithCurl, new[] { 0x1F4C3 }),
            new EmojiDetails(Emoji.Scroll, new[] { 0x1F4DC }), new EmojiDetails(Emoji.PageFacingUp, new[] { 0x1F4C4 }), new EmojiDetails(Emoji.Newspaper, new[] { 0x1F4F0 }), new EmojiDetails(Emoji.RolledUpNewspaper, new[] { 0x1F5DE, 0xFE0F }), new EmojiDetails(Emoji.BookmarkTabs, new[] { 0x1F4D1 }),
            new EmojiDetails(Emoji.Bookmark, new[] { 0x1F516 }), new EmojiDetails(Emoji.Label, new[] { 0x1F3F7, 0xFE0F }), new EmojiDetails(Emoji.MoneyBag, new[] { 0x1F4B0 }), new EmojiDetails(Emoji.BanknoteWithYenSign, new[] { 0x1F4B4 }), new EmojiDetails(Emoji.BanknoteWithDollarSign, new[] { 0x1F4B5 }),
            new EmojiDetails(Emoji.BanknoteWithEuroSign, new[] { 0x1F4B6 }), new EmojiDetails(Emoji.BanknoteWithPoundSign, new[] { 0x1F4B7 }), new EmojiDetails(Emoji.MoneyWithWings, new[] { 0x1F4B8 }), new EmojiDetails(Emoji.CreditCard, new[] { 0x1F4B3 }),
            new EmojiDetails(Emoji.ChartWithUpwardsTrendAndYenSign, new[] { 0x1F4B9 }), new EmojiDetails(Emoji.CurrencyExchange, new[] { 0x1F4B1 }), new EmojiDetails(Emoji.HeavyDollarSign, new[] { 0x1F4B2 }), new EmojiDetails(Emoji.Envelope, new[] { 0x2709, 0xFE0F }),
            new EmojiDetails(Emoji.EMailSymbol, new[] { 0x1F4E7 }), new EmojiDetails(Emoji.IncomingEnvelope, new[] { 0x1F4E8 }), new EmojiDetails(Emoji.EnvelopeWithDownwardsArrowAbove, new[] { 0x1F4E9 }), new EmojiDetails(Emoji.OutboxTray, new[] { 0x1F4E4 }),
            new EmojiDetails(Emoji.InboxTray, new[] { 0x1F4E5 }), new EmojiDetails(Emoji.Package, new[] { 0x1F4E6 }), new EmojiDetails(Emoji.ClosedMailboxWithRaisedFlag, new[] { 0x1F4EB }), new EmojiDetails(Emoji.ClosedMailboxWithLoweredFlag, new[] { 0x1F4EA }),
            new EmojiDetails(Emoji.OpenMailboxWithRaisedFlag, new[] { 0x1F4EC }), new EmojiDetails(Emoji.OpenMailboxWithLoweredFlag, new[] { 0x1F4ED }), new EmojiDetails(Emoji.Postbox, new[] { 0x1F4EE }), new EmojiDetails(Emoji.BallotBoxWithBallot, new[] { 0x1F5F3, 0xFE0F }),
            new EmojiDetails(Emoji.Pencil, new[] { 0x270F, 0xFE0F }), new EmojiDetails(Emoji.BlackNib, new[] { 0x2712, 0xFE0F }), new EmojiDetails(Emoji.LowerLeftFountainPen, new[] { 0x1F58B, 0xFE0F }), new EmojiDetails(Emoji.LowerLeftBallpointPen, new[] { 0x1F58A, 0xFE0F }),
            new EmojiDetails(Emoji.LowerLeftPaintbrush, new[] { 0x1F58C, 0xFE0F }), new EmojiDetails(Emoji.LowerLeftCrayon, new[] { 0x1F58D, 0xFE0F }), new EmojiDetails(Emoji.Memo, new[] { 0x1F4DD }), new EmojiDetails(Emoji.Briefcase, new[] { 0x1F4BC }), new EmojiDetails(Emoji.FileFolder, new[] { 0x1F4C1 }),
            new EmojiDetails(Emoji.OpenFileFolder, new[] { 0x1F4C2 }), new EmojiDetails(Emoji.CardIndexDividers, new[] { 0x1F5C2, 0xFE0F }), new EmojiDetails(Emoji.Calendar, new[] { 0x1F4C5 }), new EmojiDetails(Emoji.TearOffCalendar, new[] { 0x1F4C6 }),
            new EmojiDetails(Emoji.SpiralNotePad, new[] { 0x1F5D2, 0xFE0F }), new EmojiDetails(Emoji.SpiralCalendarPad, new[] { 0x1F5D3, 0xFE0F }), new EmojiDetails(Emoji.CardIndex, new[] { 0x1F4C7 }), new EmojiDetails(Emoji.ChartWithUpwardsTrend, new[] { 0x1F4C8 }),
            new EmojiDetails(Emoji.ChartWithDownwardsTrend, new[] { 0x1F4C9 }), new EmojiDetails(Emoji.BarChart, new[] { 0x1F4CA }), new EmojiDetails(Emoji.Clipboard, new[] { 0x1F4CB }), new EmojiDetails(Emoji.Pushpin, new[] { 0x1F4CC }), new EmojiDetails(Emoji.RoundPushpin, new[] { 0x1F4CD }),
            new EmojiDetails(Emoji.Paperclip, new[] { 0x1F4CE }), new EmojiDetails(Emoji.LinkedPaperclips, new[] { 0x1F587, 0xFE0F }), new EmojiDetails(Emoji.StraightRuler, new[] { 0x1F4CF }), new EmojiDetails(Emoji.TriangularRuler, new[] { 0x1F4D0 }),
            new EmojiDetails(Emoji.BlackScissors, new[] { 0x2702, 0xFE0F }), new EmojiDetails(Emoji.CardFileBox, new[] { 0x1F5C3, 0xFE0F }), new EmojiDetails(Emoji.FileCabinet, new[] { 0x1F5C4, 0xFE0F }), new EmojiDetails(Emoji.Wastebasket, new[] { 0x1F5D1, 0xFE0F }),
            new EmojiDetails(Emoji.Lock, new[] { 0x1F512 }), new EmojiDetails(Emoji.OpenLock, new[] { 0x1F513 }), new EmojiDetails(Emoji.LockWithInkPen, new[] { 0x1F50F }), new EmojiDetails(Emoji.ClosedLockWithKey, new[] { 0x1F510 }), new EmojiDetails(Emoji.Key, new[] { 0x1F511 }),
            new EmojiDetails(Emoji.OldKey, new[] { 0x1F5DD, 0xFE0F }), new EmojiDetails(Emoji.Hammer, new[] { 0x1F528 }), new EmojiDetails(Emoji.Pick, new[] { 0x26CF, 0xFE0F }), new EmojiDetails(Emoji.HammerAndPick, new[] { 0x2692, 0xFE0F }), new EmojiDetails(Emoji.HammerAndWrench, new[] { 0x1F6E0, 0xFE0F }),
            new EmojiDetails(Emoji.DaggerKnife, new[] { 0x1F5E1, 0xFE0F }), new EmojiDetails(Emoji.CrossedSwords, new[] { 0x2694, 0xFE0F }), new EmojiDetails(Emoji.Pistol, new[] { 0x1F52B }), new EmojiDetails(Emoji.BowAndArrow, new[] { 0x1F3F9 }), new EmojiDetails(Emoji.Shield, new[] { 0x1F6E1, 0xFE0F }),
            new EmojiDetails(Emoji.Wrench, new[] { 0x1F527 }), new EmojiDetails(Emoji.NutAndBolt, new[] { 0x1F529 }), new EmojiDetails(Emoji.Gear, new[] { 0x2699, 0xFE0F }), new EmojiDetails(Emoji.Compression, new[] { 0x1F5DC, 0xFE0F }), new EmojiDetails(Emoji.Alembic, new[] { 0x2697, 0xFE0F }),
            new EmojiDetails(Emoji.Scales, new[] { 0x2696, 0xFE0F }), new EmojiDetails(Emoji.LinkSymbol, new[] { 0x1F517 }), new EmojiDetails(Emoji.Chains, new[] { 0x26D3, 0xFE0F }), new EmojiDetails(Emoji.Syringe, new[] { 0x1F489 }), new EmojiDetails(Emoji.Pill, new[] { 0x1F48A }),
            new EmojiDetails(Emoji.SmokingSymbol, new[] { 0x1F6AC }), new EmojiDetails(Emoji.Coffin, new[] { 0x26B0, 0xFE0F }), new EmojiDetails(Emoji.FuneralUrn, new[] { 0x26B1, 0xFE0F }), new EmojiDetails(Emoji.Moyai, new[] { 0x1F5FF }), new EmojiDetails(Emoji.OilDrum, new[] { 0x1F6E2, 0xFE0F }),
            new EmojiDetails(Emoji.CrystalBall, new[] { 0x1F52E }), new EmojiDetails(Emoji.ShoppingTrolley, new[] { 0x1F6D2 }), new EmojiDetails(Emoji.AutomatedTellerMachine, new[] { 0x1F3E7 }), new EmojiDetails(Emoji.PutLitterInItsPlaceSymbol, new[] { 0x1F6AE }),
            new EmojiDetails(Emoji.PotableWaterSymbol, new[] { 0x1F6B0 }), new EmojiDetails(Emoji.WheelchairSymbol, new[] { 0x267F }), new EmojiDetails(Emoji.MensSymbol, new[] { 0x1F6B9 }), new EmojiDetails(Emoji.WomensSymbol, new[] { 0x1F6BA }), new EmojiDetails(Emoji.Restroom, new[] { 0x1F6BB }),
            new EmojiDetails(Emoji.BabySymbol, new[] { 0x1F6BC }), new EmojiDetails(Emoji.WaterCloset, new[] { 0x1F6BE }), new EmojiDetails(Emoji.PassportControl, new[] { 0x1F6C2 }), new EmojiDetails(Emoji.Customs, new[] { 0x1F6C3 }), new EmojiDetails(Emoji.BaggageClaim, new[] { 0x1F6C4 }),
            new EmojiDetails(Emoji.LeftLuggage, new[] { 0x1F6C5 }), new EmojiDetails(Emoji.WarningSign, new[] { 0x26A0, 0xFE0F }), new EmojiDetails(Emoji.ChildrenCrossing, new[] { 0x1F6B8 }), new EmojiDetails(Emoji.NoEntry, new[] { 0x26D4 }), new EmojiDetails(Emoji.NoEntrySign, new[] { 0x1F6AB }),
            new EmojiDetails(Emoji.NoBicycles, new[] { 0x1F6B3 }), new EmojiDetails(Emoji.NoSmokingSymbol, new[] { 0x1F6AD }), new EmojiDetails(Emoji.DoNotLitterSymbol, new[] { 0x1F6AF }), new EmojiDetails(Emoji.NonPotableWaterSymbol, new[] { 0x1F6B1 }),
            new EmojiDetails(Emoji.NoPedestrians, new[] { 0x1F6B7 }), new EmojiDetails(Emoji.NoMobilePhones, new[] { 0x1F4F5 }), new EmojiDetails(Emoji.NoOneUnderEighteenSymbol, new[] { 0x1F51E }), new EmojiDetails(Emoji.RadioactiveSign, new[] { 0x2622, 0xFE0F }),
            new EmojiDetails(Emoji.BiohazardSign, new[] { 0x2623, 0xFE0F }), new EmojiDetails(Emoji.UpwardsBlackArrow, new[] { 0x2B06, 0xFE0F }), new EmojiDetails(Emoji.NorthEastArrow, new[] { 0x2197, 0xFE0F }), new EmojiDetails(Emoji.BlackRightwardsArrow, new[] { 0x27A1, 0xFE0F }),
            new EmojiDetails(Emoji.SouthEastArrow, new[] { 0x2198, 0xFE0F }), new EmojiDetails(Emoji.DownwardsBlackArrow, new[] { 0x2B07, 0xFE0F }), new EmojiDetails(Emoji.SouthWestArrow, new[] { 0x2199, 0xFE0F }), new EmojiDetails(Emoji.LeftwardsBlackArrow, new[] { 0x2B05, 0xFE0F }),
            new EmojiDetails(Emoji.NorthWestArrow, new[] { 0x2196, 0xFE0F }), new EmojiDetails(Emoji.UpDownArrow, new[] { 0x2195, 0xFE0F }), new EmojiDetails(Emoji.LeftRightArrow, new[] { 0x2194, 0xFE0F }), new EmojiDetails(Emoji.LeftwardsArrowWithHook, new[] { 0x21A9, 0xFE0F }),
            new EmojiDetails(Emoji.RightwardsArrowWithHook, new[] { 0x21AA, 0xFE0F }), new EmojiDetails(Emoji.ArrowPointingRightwardsThenCurvingUpwards, new[] { 0x2934, 0xFE0F }), new EmojiDetails(Emoji.ArrowPointingRightwardsThenCurvingDownwards, new[] { 0x2935, 0xFE0F }),
            new EmojiDetails(Emoji.ClockwiseDownwardsAndUpwardsOpenCircleArrows, new[] { 0x1F503 }), new EmojiDetails(Emoji.AnticlockwiseDownwardsAndUpwardsOpenCircleArrows, new[] { 0x1F504 }), new EmojiDetails(Emoji.BackWithLeftwardsArrowAbove, new[] { 0x1F519 }),
            new EmojiDetails(Emoji.EndWithLeftwardsArrowAbove, new[] { 0x1F51A }), new EmojiDetails(Emoji.OnWithExclamationMarkWithLeftRightArrowAbove, new[] { 0x1F51B }), new EmojiDetails(Emoji.SoonWithRightwardsArrowAbove, new[] { 0x1F51C }),
            new EmojiDetails(Emoji.TopWithUpwardsArrowAbove, new[] { 0x1F51D }), new EmojiDetails(Emoji.PlaceOfWorship, new[] { 0x1F6D0 }), new EmojiDetails(Emoji.AtomSymbol, new[] { 0x269B, 0xFE0F }), new EmojiDetails(Emoji.OmSymbol, new[] { 0x1F549, 0xFE0F }),
            new EmojiDetails(Emoji.StarOfDavid, new[] { 0x2721, 0xFE0F }), new EmojiDetails(Emoji.WheelOfDharma, new[] { 0x2638, 0xFE0F }), new EmojiDetails(Emoji.YinYang, new[] { 0x262F, 0xFE0F }), new EmojiDetails(Emoji.LatinCross, new[] { 0x271D, 0xFE0F }),
            new EmojiDetails(Emoji.OrthodoxCross, new[] { 0x2626, 0xFE0F }), new EmojiDetails(Emoji.StarAndCrescent, new[] { 0x262A, 0xFE0F }), new EmojiDetails(Emoji.PeaceSymbol, new[] { 0x262E, 0xFE0F }), new EmojiDetails(Emoji.MenorahWithNineBranches, new[] { 0x1F54E }),
            new EmojiDetails(Emoji.SixPointedStarWithMiddleDot, new[] { 0x1F52F }), new EmojiDetails(Emoji.Aries, new[] { 0x2648 }), new EmojiDetails(Emoji.Taurus, new[] { 0x2649 }), new EmojiDetails(Emoji.Gemini, new[] { 0x264A }), new EmojiDetails(Emoji.Cancer, new[] { 0x264B }),
            new EmojiDetails(Emoji.Leo, new[] { 0x264C }), new EmojiDetails(Emoji.Virgo, new[] { 0x264D }), new EmojiDetails(Emoji.Libra, new[] { 0x264E }), new EmojiDetails(Emoji.Scorpius, new[] { 0x264F }), new EmojiDetails(Emoji.Sagittarius, new[] { 0x2650 }),
            new EmojiDetails(Emoji.Capricorn, new[] { 0x2651 }), new EmojiDetails(Emoji.Aquarius, new[] { 0x2652 }), new EmojiDetails(Emoji.Pisces, new[] { 0x2653 }), new EmojiDetails(Emoji.Ophiuchus, new[] { 0x26CE }), new EmojiDetails(Emoji.TwistedRightwardsArrows, new[] { 0x1F500 }),
            new EmojiDetails(Emoji.ClockwiseRightwardsAndLeftwardsOpenCircleArrows, new[] { 0x1F501 }), new EmojiDetails(Emoji.ClockwiseRightwardsAndLeftwardsOpenCircleArrowsWithCircledOneOverlay, new[] { 0x1F502 }), new EmojiDetails(Emoji.BlackRightPointingTriangle, new[] { 0x25B6, 0xFE0F }),
            new EmojiDetails(Emoji.BlackRightPointingDoubleTriangle, new[] { 0x23E9 }), new EmojiDetails(Emoji.BlackRightPointingDoubleTriangleWithVerticalBar, new[] { 0x23ED, 0xFE0F }), new EmojiDetails(Emoji.BlackRightPointingTriangleWithDoubleVerticalBar, new[] { 0x23EF, 0xFE0F }),
            new EmojiDetails(Emoji.BlackLeftPointingTriangle, new[] { 0x25C0, 0xFE0F }), new EmojiDetails(Emoji.BlackLeftPointingDoubleTriangle, new[] { 0x23EA }), new EmojiDetails(Emoji.BlackLeftPointingDoubleTriangleWithVerticalBar, new[] { 0x23EE, 0xFE0F }),
            new EmojiDetails(Emoji.UpPointingSmallRedTriangle, new[] { 0x1F53C }), new EmojiDetails(Emoji.BlackUpPointingDoubleTriangle, new[] { 0x23EB }), new EmojiDetails(Emoji.DownPointingSmallRedTriangle, new[] { 0x1F53D }), new EmojiDetails(Emoji.BlackDownPointingDoubleTriangle, new[] { 0x23EC }),
            new EmojiDetails(Emoji.DoubleVerticalBar, new[] { 0x23F8, 0xFE0F }), new EmojiDetails(Emoji.BlackSquareForStop, new[] { 0x23F9, 0xFE0F }), new EmojiDetails(Emoji.BlackCircleForRecord, new[] { 0x23FA, 0xFE0F }), new EmojiDetails(Emoji.EjectSymbol, new[] { 0x23CF, 0xFE0F }),
            new EmojiDetails(Emoji.Cinema, new[] { 0x1F3A6 }), new EmojiDetails(Emoji.LowBrightnessSymbol, new[] { 0x1F505 }), new EmojiDetails(Emoji.HighBrightnessSymbol, new[] { 0x1F506 }), new EmojiDetails(Emoji.AntennaWithBars, new[] { 0x1F4F6 }), new EmojiDetails(Emoji.VibrationMode, new[] { 0x1F4F3 }),
            new EmojiDetails(Emoji.MobilePhoneOff, new[] { 0x1F4F4 }), new EmojiDetails(Emoji.BlackUniversalRecyclingSymbol, new[] { 0x267B, 0xFE0F }), new EmojiDetails(Emoji.FleurDeLis, new[] { 0x269C, 0xFE0F }), new EmojiDetails(Emoji.TridentEmblem, new[] { 0x1F531 }),
            new EmojiDetails(Emoji.NameBadge, new[] { 0x1F4DB }), new EmojiDetails(Emoji.JapaneseSymbolForBeginner, new[] { 0x1F530 }), new EmojiDetails(Emoji.HeavyLargeCircle, new[] { 0x2B55 }), new EmojiDetails(Emoji.WhiteHeavyCheckMark, new[] { 0x2705 }),
            new EmojiDetails(Emoji.BallotBoxWithCheck, new[] { 0x2611, 0xFE0F }), new EmojiDetails(Emoji.HeavyCheckMark, new[] { 0x2714, 0xFE0F }), new EmojiDetails(Emoji.HeavyMultiplicationX, new[] { 0x2716, 0xFE0F }), new EmojiDetails(Emoji.CrossMark, new[] { 0x274C }),
            new EmojiDetails(Emoji.NegativeSquaredCrossMark, new[] { 0x274E }), new EmojiDetails(Emoji.HeavyPlusSign, new[] { 0x2795 }), new EmojiDetails(Emoji.HeavyMinusSign, new[] { 0x2796 }), new EmojiDetails(Emoji.HeavyDivisionSign, new[] { 0x2797 }), new EmojiDetails(Emoji.CurlyLoop, new[] { 0x27B0 }),
            new EmojiDetails(Emoji.DoubleCurlyLoop, new[] { 0x27BF }), new EmojiDetails(Emoji.PartAlternationMark, new[] { 0x303D, 0xFE0F }), new EmojiDetails(Emoji.EightSpokedAsterisk, new[] { 0x2733, 0xFE0F }), new EmojiDetails(Emoji.EightPointedBlackStar, new[] { 0x2734, 0xFE0F }),
            new EmojiDetails(Emoji.Sparkle, new[] { 0x2747, 0xFE0F }), new EmojiDetails(Emoji.DoubleExclamationMark, new[] { 0x203C, 0xFE0F }), new EmojiDetails(Emoji.ExclamationQuestionMark, new[] { 0x2049, 0xFE0F }), new EmojiDetails(Emoji.BlackQuestionMarkOrnament, new[] { 0x2753 }),
            new EmojiDetails(Emoji.WhiteQuestionMarkOrnament, new[] { 0x2754 }), new EmojiDetails(Emoji.WhiteExclamationMarkOrnament, new[] { 0x2755 }), new EmojiDetails(Emoji.HeavyExclamationMarkSymbol, new[] { 0x2757 }), new EmojiDetails(Emoji.CopyrightSign, new[] { 0xA9, 0xFE0F }),
            new EmojiDetails(Emoji.RegisteredSign, new[] { 0xAE, 0xFE0F }), new EmojiDetails(Emoji.TradeMarkSign, new[] { 0x2122, 0xFE0F }), new EmojiDetails(Emoji.KeycapTen, new[] { 0x1F51F }), new EmojiDetails(Emoji.HundredPointsSymbol, new[] { 0x1F4AF }),
            new EmojiDetails(Emoji.InputSymbolForLatinCapitalLetters, new[] { 0x1F520 }), new EmojiDetails(Emoji.InputSymbolForLatinSmallLetters, new[] { 0x1F521 }), new EmojiDetails(Emoji.InputSymbolForNumbers, new[] { 0x1F522 }), new EmojiDetails(Emoji.InputSymbolForSymbols, new[] { 0x1F523 }),
            new EmojiDetails(Emoji.InputSymbolForLatinLetters, new[] { 0x1F524 }), new EmojiDetails(Emoji.NegativeSquaredLatinCapitalLetterA, new[] { 0x1F170, 0xFE0F }), new EmojiDetails(Emoji.NegativeSquaredAB, new[] { 0x1F18E }),
            new EmojiDetails(Emoji.NegativeSquaredLatinCapitalLetterB, new[] { 0x1F171, 0xFE0F }), new EmojiDetails(Emoji.SquaredCL, new[] { 0x1F191 }), new EmojiDetails(Emoji.SquaredCool, new[] { 0x1F192 }), new EmojiDetails(Emoji.SquaredFree, new[] { 0x1F193 }),
            new EmojiDetails(Emoji.InformationSource, new[] { 0x2139, 0xFE0F }), new EmojiDetails(Emoji.SquaredID, new[] { 0x1F194 }), new EmojiDetails(Emoji.CircledLatinCapitalLetterM, new[] { 0x24C2, 0xFE0F }), new EmojiDetails(Emoji.SquaredNew, new[] { 0x1F195 }),
            new EmojiDetails(Emoji.SquaredNG, new[] { 0x1F196 }), new EmojiDetails(Emoji.NegativeSquaredLatinCapitalLetterO, new[] { 0x1F17E, 0xFE0F }), new EmojiDetails(Emoji.SquaredOK, new[] { 0x1F197 }), new EmojiDetails(Emoji.NegativeSquaredLatinCapitalLetterP, new[] { 0x1F17F, 0xFE0F }),
            new EmojiDetails(Emoji.SquaredSOS, new[] { 0x1F198 }), new EmojiDetails(Emoji.SquaredUpWithExclamationMark, new[] { 0x1F199 }), new EmojiDetails(Emoji.SquaredVs, new[] { 0x1F19A }), new EmojiDetails(Emoji.SquaredKatakanaKoko, new[] { 0x1F201 }),
            new EmojiDetails(Emoji.SquaredKatakanaSa, new[] { 0x1F202, 0xFE0F }), new EmojiDetails(Emoji.SquaredCJKUnifiedIdeograph6708, new[] { 0x1F237, 0xFE0F }), new EmojiDetails(Emoji.SquaredCJKUnifiedIdeograph6709, new[] { 0x1F236 }),
            new EmojiDetails(Emoji.SquaredCJKUnifiedIdeograph6307, new[] { 0x1F22F }), new EmojiDetails(Emoji.CircledIdeographAdvantage, new[] { 0x1F250 }), new EmojiDetails(Emoji.SquaredCJKUnifiedIdeograph5272, new[] { 0x1F239 }), new EmojiDetails(Emoji.SquaredCJKUnifiedIdeograph7121, new[] { 0x1F21A }),
            new EmojiDetails(Emoji.SquaredCJKUnifiedIdeograph7981, new[] { 0x1F232 }), new EmojiDetails(Emoji.CircledIdeographAccept, new[] { 0x1F251 }), new EmojiDetails(Emoji.SquaredCJKUnifiedIdeograph7533, new[] { 0x1F238 }), new EmojiDetails(Emoji.SquaredCJKUnifiedIdeograph5408, new[] { 0x1F234 }),
            new EmojiDetails(Emoji.SquaredCJKUnifiedIdeograph7a7a, new[] { 0x1F233 }), new EmojiDetails(Emoji.CircledIdeographCongratulation, new[] { 0x3297, 0xFE0F }), new EmojiDetails(Emoji.CircledIdeographSecret, new[] { 0x3299, 0xFE0F }),
            new EmojiDetails(Emoji.SquaredCJKUnifiedIdeograph55b6, new[] { 0x1F23A }), new EmojiDetails(Emoji.SquaredCJKUnifiedIdeograph6e80, new[] { 0x1F235 }), new EmojiDetails(Emoji.BlackSmallSquare, new[] { 0x25AA, 0xFE0F }), new EmojiDetails(Emoji.WhiteSmallSquare, new[] { 0x25AB, 0xFE0F }),
            new EmojiDetails(Emoji.BlackLargeSquare, new[] { 0x2B1B }), new EmojiDetails(Emoji.WhiteLargeSquare, new[] { 0x2B1C }), new EmojiDetails(Emoji.LargeOrangeDiamond, new[] { 0x1F536 }), new EmojiDetails(Emoji.LargeBlueDiamond, new[] { 0x1F537 }),
            new EmojiDetails(Emoji.SmallOrangeDiamond, new[] { 0x1F538 }), new EmojiDetails(Emoji.SmallBlueDiamond, new[] { 0x1F539 }), new EmojiDetails(Emoji.UpPointingRedTriangle, new[] { 0x1F53A }), new EmojiDetails(Emoji.DownPointingRedTriangle, new[] { 0x1F53B }),
            new EmojiDetails(Emoji.DiamondShapeWithADotInside, new[] { 0x1F4A0 }), new EmojiDetails(Emoji.RadioButton, new[] { 0x1F518 }), new EmojiDetails(Emoji.BlackSquareButton, new[] { 0x1F532 }), new EmojiDetails(Emoji.WhiteSquareButton, new[] { 0x1F533 }),
            new EmojiDetails(Emoji.MediumWhiteCircle, new[] { 0x26AA }), new EmojiDetails(Emoji.MediumBlackCircle, new[] { 0x26AB }), new EmojiDetails(Emoji.LargeRedCircle, new[] { 0x1F534 }), new EmojiDetails(Emoji.LargeBlueCircle, new[] { 0x1F535 }), new EmojiDetails(Emoji.ChequeredFlag, new[] { 0x1F3C1 }),
            new EmojiDetails(Emoji.TriangularFlagOnPost, new[] { 0x1F6A9 }), new EmojiDetails(Emoji.CrossedFlags, new[] { 0x1F38C }), new EmojiDetails(Emoji.WavingBlackFlag, new[] { 0x1F3F4 }), new EmojiDetails(Emoji.WavingWhiteFlag, new[] { 0x1F3F3, 0xFE0F }),
            new EmojiDetails(Emoji.DinoCat, new[] { 0x1F431, 0x200D, 0x1F409 }), new EmojiDetails(Emoji.StuntCat, new[] { 0x1F431, 0x200D, 0x1F3CD }), new EmojiDetails(Emoji.HipsterCat, new[] { 0x1F431, 0x200D, 0x1F453 }), new EmojiDetails(Emoji.HackerCat, new[] { 0x1F431, 0x200D, 0x1F4BB }),
            new EmojiDetails(Emoji.AstroCat, new[] { 0x1F431, 0x200D, 0x1F680 }), new EmojiDetails(Emoji.NinjaCat, new[] { 0x1F431, 0x200D, 0x1F464 }), new EmojiDetails(Emoji.FamilyManManBabyGirl, new[] { 0x1F468, 0x200D, 0x1F468, 0x200D, 0x1F476, 0x200D, 0x1F467 }),
            new EmojiDetails(Emoji.FamilyManManBabyBaby, new[] { 0x1F468, 0x200D, 0x1F468, 0x200D, 0x1F476, 0x200D, 0x1F476 }), new EmojiDetails(Emoji.FamilyManWomanBoyGirl, new[] { 0x1F468, 0x200D, 0x1F469, 0x200D, 0x1F466, 0x200D, 0x1F467 }),
            new EmojiDetails(Emoji.FamilyManBabyBoy, new[] { 0x1F468, 0x200D, 0x1F476, 0x200D, 0x1F466 }), new EmojiDetails(Emoji.FamilyWomanGirlBaby, new[] { 0x1F469, 0x200D, 0x1F467, 0x200D, 0x1F476 }), new EmojiDetails(Emoji.FamilyManBabyGirl, new[] { 0x1F468, 0x200D, 0x1F476, 0x200D, 0x1F467 }),
            new EmojiDetails(Emoji.FamilyManBabyBaby, new[] { 0x1F468, 0x200D, 0x1F476, 0x200D, 0x1F476 }), new EmojiDetails(Emoji.FamilyWomanBoyGirl, new[] { 0x1F469, 0x200D, 0x1F466, 0x200D, 0x1F467 }),
            new EmojiDetails(Emoji.FamilyManWomanBoyBaby, new[] { 0x1F468, 0x200D, 0x1F469, 0x200D, 0x1F466, 0x200D, 0x1F476 }), new EmojiDetails(Emoji.FamilyManWomanGirlBaby, new[] { 0x1F468, 0x200D, 0x1F469, 0x200D, 0x1F467, 0x200D, 0x1F476 }),
            new EmojiDetails(Emoji.FamilyManWomanBaby, new[] { 0x1F468, 0x200D, 0x1F469, 0x200D, 0x1F476 }), new EmojiDetails(Emoji.FamilyManWomanBabyBoy, new[] { 0x1F468, 0x200D, 0x1F469, 0x200D, 0x1F476, 0x200D, 0x1F466 }),
            new EmojiDetails(Emoji.FamilyWomanManBabyGirl, new[] { 0x1F469, 0x200D, 0x1F468, 0x200D, 0x1F476, 0x200D, 0x1F467 }), new EmojiDetails(Emoji.FamilyWomanManBabyBaby, new[] { 0x1F469, 0x200D, 0x1F468, 0x200D, 0x1F476, 0x200D, 0x1F476 }),
            new EmojiDetails(Emoji.FamilyWomanWomanBoyGirl, new[] { 0x1F469, 0x200D, 0x1F469, 0x200D, 0x1F466, 0x200D, 0x1F467 }), new EmojiDetails(Emoji.FamilyWomanWomanBoyBaby, new[] { 0x1F469, 0x200D, 0x1F469, 0x200D, 0x1F466, 0x200D, 0x1F476 }),
            new EmojiDetails(Emoji.FamilyWomanManBabyBoy, new[] { 0x1F469, 0x200D, 0x1F468, 0x200D, 0x1F476, 0x200D, 0x1F466 }), new EmojiDetails(Emoji.FamilyWomanManBaby, new[] { 0x1F469, 0x200D, 0x1F468, 0x200D, 0x1F476 }),
            new EmojiDetails(Emoji.FamilyWomanManGirlBaby, new[] { 0x1F469, 0x200D, 0x1F468, 0x200D, 0x1F467, 0x200D, 0x1F476 }), new EmojiDetails(Emoji.FamilyWomanManGirlGirl, new[] { 0x1F469, 0x200D, 0x1F468, 0x200D, 0x1F467, 0x200D, 0x1F467 }),
            new EmojiDetails(Emoji.FamilyWomanManGirlBoy, new[] { 0x1F469, 0x200D, 0x1F468, 0x200D, 0x1F467, 0x200D, 0x1F466 }), new EmojiDetails(Emoji.FamilyWomanManGirl, new[] { 0x1F469, 0x200D, 0x1F468, 0x200D, 0x1F467 }),
            new EmojiDetails(Emoji.FamilyWomanManBoyBaby, new[] { 0x1F469, 0x200D, 0x1F468, 0x200D, 0x1F466, 0x200D, 0x1F476 }), new EmojiDetails(Emoji.FamilyWomanManBoyGirl, new[] { 0x1F469, 0x200D, 0x1F468, 0x200D, 0x1F466, 0x200D, 0x1F467 }),
            new EmojiDetails(Emoji.FamilyWomanManBoyBoy, new[] { 0x1F469, 0x200D, 0x1F468, 0x200D, 0x1F466, 0x200D, 0x1F466 }), new EmojiDetails(Emoji.FamilyWomanManBoy, new[] { 0x1F469, 0x200D, 0x1F468, 0x200D, 0x1F466 }),
            new EmojiDetails(Emoji.FamilyManWomanBabyBaby, new[] { 0x1F468, 0x200D, 0x1F469, 0x200D, 0x1F476, 0x200D, 0x1F476 }), new EmojiDetails(Emoji.FamilyManWomanBabyGirl, new[] { 0x1F468, 0x200D, 0x1F469, 0x200D, 0x1F476, 0x200D, 0x1F467 }),
            new EmojiDetails(Emoji.FamilyWomanWomanGirlBaby, new[] { 0x1F469, 0x200D, 0x1F469, 0x200D, 0x1F467, 0x200D, 0x1F476 }), new EmojiDetails(Emoji.FamilyWomanWomanBaby, new[] { 0x1F469, 0x200D, 0x1F469, 0x200D, 0x1F476 }),
            new EmojiDetails(Emoji.FamilyWomanWomanBabyBoy, new[] { 0x1F469, 0x200D, 0x1F469, 0x200D, 0x1F476, 0x200D, 0x1F466 }), new EmojiDetails(Emoji.FamilyWomanWomanBabyGirl, new[] { 0x1F469, 0x200D, 0x1F469, 0x200D, 0x1F476, 0x200D, 0x1F467 }),
            new EmojiDetails(Emoji.FamilyWomanWomanBabyBaby, new[] { 0x1F469, 0x200D, 0x1F469, 0x200D, 0x1F476, 0x200D, 0x1F476 }), new EmojiDetails(Emoji.FamilyWomanBaby, new[] { 0x1F469, 0x200D, 0x1F476 }), new EmojiDetails(Emoji.FamilyWomanBabyBoy, new[] { 0x1F469, 0x200D, 0x1F476, 0x200D, 0x1F466 }),
            new EmojiDetails(Emoji.FamilyWomanBabyGirl, new[] { 0x1F469, 0x200D, 0x1F476, 0x200D, 0x1F467 }), new EmojiDetails(Emoji.FamilyWomanBabyBaby, new[] { 0x1F469, 0x200D, 0x1F476, 0x200D, 0x1F476 }), new EmojiDetails(Emoji.FamilyManBoyGirl, new[] { 0x1F468, 0x200D, 0x1F466, 0x200D, 0x1F467 }),
            new EmojiDetails(Emoji.FamilyManBoyBaby, new[] { 0x1F468, 0x200D, 0x1F466, 0x200D, 0x1F476 }), new EmojiDetails(Emoji.FamilyManGirlBaby, new[] { 0x1F468, 0x200D, 0x1F467, 0x200D, 0x1F476 }), new EmojiDetails(Emoji.FamilyWomanBoyBaby, new[] { 0x1F469, 0x200D, 0x1F466, 0x200D, 0x1F476 }),
            new EmojiDetails(Emoji.FamilyManBaby, new[] { 0x1F468, 0x200D, 0x1F476 }), new EmojiDetails(Emoji.FamilyManManBoyGirl, new[] { 0x1F468, 0x200D, 0x1F468, 0x200D, 0x1F466, 0x200D, 0x1F467 }),
            new EmojiDetails(Emoji.FamilyManManBoyBaby, new[] { 0x1F468, 0x200D, 0x1F468, 0x200D, 0x1F466, 0x200D, 0x1F476 }), new EmojiDetails(Emoji.FamilyManManGirlBaby, new[] { 0x1F468, 0x200D, 0x1F468, 0x200D, 0x1F467, 0x200D, 0x1F476 }),
            new EmojiDetails(Emoji.FamilyManManBaby, new[] { 0x1F468, 0x200D, 0x1F468, 0x200D, 0x1F476 }), new EmojiDetails(Emoji.FamilyManManBabyBoy, new[] { 0x1F468, 0x200D, 0x1F468, 0x200D, 0x1F476, 0x200D, 0x1F466 })
        };

        /// <summary>
        /// Gets the emoji.
        /// </summary>
        /// <param name="emoji">The emoji.</param>
        /// <param name="skinTone">The skin tone.</param>
        /// <returns>A unicode string for hte emoji</returns>
        public static string GetEmoji(this Emoji emoji, EmojiSkinTone? skinTone = null)
        {
            var details = EmojiArray.FirstOrDefault(x => x.Emoji == emoji);

            var code = string.Empty;
            foreach (var i in details.Code)
            {
                code = code + char.ConvertFromUtf32(i);
            }

            if (skinTone.HasValue && details.SupportsModifier)
            {
                return code + skinTone.Value.ToModifierCharacter();
            }

            return code;
        }

        /// <summary>
        /// Checks to see if the given emoji supports the multi color modifier
        /// </summary>
        /// <param name="emoji">The emoji.</param>
        /// <returns>true if it does</returns>
        public static bool SupportsMultipleColors(this Emoji emoji)
        {
            var details = EmojiArray.FirstOrDefault(x => x.Emoji == emoji);
            return details.SupportsModifier;
        }

        private static string ToModifierCharacter(this EmojiSkinTone skinTone)
        {
            string hexadecimalCode;
            switch (skinTone)
            {
                case EmojiSkinTone.Type12:
                    hexadecimalCode = "1F3FB";
                    break;
                case EmojiSkinTone.Type3:
                    hexadecimalCode = "1F3FC";
                    break;
                case EmojiSkinTone.Type4:
                    hexadecimalCode = "1F3FD";
                    break;
                case EmojiSkinTone.Type5:
                    hexadecimalCode = "1F3FE";
                    break;
                case EmojiSkinTone.Type6:
                    hexadecimalCode = "1F3FF";
                    break;
                default:
                    return string.Empty; // generic yellow color, no modifier
            }

            var code = int.Parse(hexadecimalCode, NumberStyles.HexNumber);
            return char.ConvertFromUtf32(code);
        }

        private struct EmojiDetails
        {
            public Emoji Emoji { get; }

            public int[] Code { get; }

            public bool SupportsModifier { get; }

            public EmojiDetails(Emoji emoji, int[] code)
            {
                Emoji = emoji;
                Code = code;
                SupportsModifier = false;
            }

            public EmojiDetails(Emoji emoji, int[] code, bool supportsModifier)
            {
                Emoji = emoji;
                Code = code;
                SupportsModifier = supportsModifier;
            }
        }
    }
}