#pragma once
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnimatedVisuals
{
    ref class BirthdayCake sealed : public Microsoft::UI::Xaml::Controls::IAnimatedVisualSource
    {
    public:
        virtual Microsoft::UI::Xaml::Controls::IAnimatedVisual^ TryCreateAnimatedVisual(
            Windows::UI::Composition::Compositor^ compositor,
            Platform::Object^* diagnostics);
    };
}