//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunityToolkit.WinUI.UI.Controls.Design {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CommunityToolkit.WinUI.UI.Controls.Design.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string CategoryAppearance {
            get {
                return ResourceManager.GetString("CategoryAppearance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Brush.
        /// </summary>
        internal static string CategoryBrush {
            get {
                return ResourceManager.GetString("CategoryBrush", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string CategoryCommon {
            get {
                return ResourceManager.GetString("CategoryCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Drop Shadow.
        /// </summary>
        internal static string CategoryDropShadow {
            get {
                return ResourceManager.GetString("CategoryDropShadow", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Interactions.
        /// </summary>
        internal static string CategoryInteractions {
            get {
                return ResourceManager.GetString("CategoryInteractions", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string CategoryLayout {
            get {
                return ResourceManager.GetString("CategoryLayout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Markdown Style - Code.
        /// </summary>
        internal static string CategoryMarkdownCodeStyle {
            get {
                return ResourceManager.GetString("CategoryMarkdownCodeStyle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Markdown Style - Header {0}.
        /// </summary>
        internal static string CategoryMarkdownHeaderStyle {
            get {
                return ResourceManager.GetString("CategoryMarkdownHeaderStyle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Markdown Style - List.
        /// </summary>
        internal static string CategoryMarkdownListStyle {
            get {
                return ResourceManager.GetString("CategoryMarkdownListStyle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Markdown Style - Quote.
        /// </summary>
        internal static string CategoryMarkdownQuoteStyle {
            get {
                return ResourceManager.GetString("CategoryMarkdownQuoteStyle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Markdown Style.
        /// </summary>
        internal static string CategoryMarkdownStyle {
            get {
                return ResourceManager.GetString("CategoryMarkdownStyle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Markdown Style - Table.
        /// </summary>
        internal static string CategoryMarkdownTableStyle {
            get {
                return ResourceManager.GetString("CategoryMarkdownTableStyle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string CategoryText {
            get {
                return ResourceManager.GetString("CategoryText", resourceCulture);
            }
        }
    }
}
