//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Microsoft.Toolkit.Uwp.UI.Controls.Design.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Microsoft.Toolkit.Uwp.UI.Controls.Design.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string CategoryAppearance {
            get {
                return ResourceManager.GetString("CategoryAppearance", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cell Binding.
        /// </summary>
        internal static string CategoryCellBinding {
            get {
                return ResourceManager.GetString("CategoryCellBinding", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Cell Template.
        /// </summary>
        internal static string CategoryCellTemplate {
            get {
                return ResourceManager.GetString("CategoryCellTemplate", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        internal static string CategoryColumns {
            get {
                return ResourceManager.GetString("CategoryColumns", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string CategoryCommon {
            get {
                return ResourceManager.GetString("CategoryCommon", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Grid Lines.
        /// </summary>
        internal static string CategoryGridLines {
            get {
                return ResourceManager.GetString("CategoryGridLines", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        internal static string CategoryHeader {
            get {
                return ResourceManager.GetString("CategoryHeader", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Headers.
        /// </summary>
        internal static string CategoryHeaders {
            get {
                return ResourceManager.GetString("CategoryHeaders", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string CategoryLayout {
            get {
                return ResourceManager.GetString("CategoryLayout", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        internal static string CategoryRows {
            get {
                return ResourceManager.GetString("CategoryRows", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Sort.
        /// </summary>
        internal static string CategorySort {
            get {
                return ResourceManager.GetString("CategorySort", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string CategoryText {
            get {
                return ResourceManager.GetString("CategoryText", resourceCulture);
            }
        }
    }
}
